// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.33.1
// source: grpcproto/vpnserver.proto

package grpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartAwgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tunnel string `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	Config string `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *StartAwgRequest) Reset() {
	*x = StartAwgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartAwgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAwgRequest) ProtoMessage() {}

func (x *StartAwgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAwgRequest.ProtoReflect.Descriptor instead.
func (*StartAwgRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{0}
}

func (x *StartAwgRequest) GetTunnel() string {
	if x != nil {
		return x.Tunnel
	}
	return ""
}

func (x *StartAwgRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type GetOutlineLastErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetOutlineLastErrorResponse) Reset() {
	*x = GetOutlineLastErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOutlineLastErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutlineLastErrorResponse) ProtoMessage() {}

func (x *GetOutlineLastErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutlineLastErrorResponse.ProtoReflect.Descriptor instead.
func (*GetOutlineLastErrorResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{1}
}

func (x *GetOutlineLastErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartOutlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *StartOutlineRequest) Reset() {
	*x = StartOutlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartOutlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOutlineRequest) ProtoMessage() {}

func (x *StartOutlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOutlineRequest.ProtoReflect.Descriptor instead.
func (*StartOutlineRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{2}
}

func (x *StartOutlineRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type StartOutlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *StartOutlineResponse) Reset() {
	*x = StartOutlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartOutlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOutlineResponse) ProtoMessage() {}

func (x *StartOutlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOutlineResponse.ProtoReflect.Descriptor instead.
func (*StartOutlineResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{3}
}

func (x *StartOutlineResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type CouldStartResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CouldStartResponce) Reset() {
	*x = CouldStartResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouldStartResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouldStartResponce) ProtoMessage() {}

func (x *CouldStartResponce) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouldStartResponce.ProtoReflect.Descriptor instead.
func (*CouldStartResponce) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{4}
}

func (x *CouldStartResponce) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type CheckServerAliveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port    int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *CheckServerAliveRequest) Reset() {
	*x = CheckServerAliveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckServerAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckServerAliveRequest) ProtoMessage() {}

func (x *CheckServerAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckServerAliveRequest.ProtoReflect.Descriptor instead.
func (*CheckServerAliveRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{5}
}

func (x *CheckServerAliveRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CheckServerAliveRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CheckServerAliveResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CheckServerAliveResponce) Reset() {
	*x = CheckServerAliveResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckServerAliveResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckServerAliveResponce) ProtoMessage() {}

func (x *CheckServerAliveResponce) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckServerAliveResponce.ProtoReflect.Descriptor instead.
func (*CheckServerAliveResponce) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{6}
}

func (x *CheckServerAliveResponce) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type StartCloakClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalHost string `protobuf:"bytes,1,opt,name=localHost,proto3" json:"localHost,omitempty"`
	LocalPort string `protobuf:"bytes,2,opt,name=localPort,proto3" json:"localPort,omitempty"`
	Config    string `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Udp       bool   `protobuf:"varint,4,opt,name=udp,proto3" json:"udp,omitempty"`
}

func (x *StartCloakClientRequest) Reset() {
	*x = StartCloakClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCloakClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCloakClientRequest) ProtoMessage() {}

func (x *StartCloakClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCloakClientRequest.ProtoReflect.Descriptor instead.
func (*StartCloakClientRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{7}
}

func (x *StartCloakClientRequest) GetLocalHost() string {
	if x != nil {
		return x.LocalHost
	}
	return ""
}

func (x *StartCloakClientRequest) GetLocalPort() string {
	if x != nil {
		return x.LocalPort
	}
	return ""
}

func (x *StartCloakClientRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StartCloakClientRequest) GetUdp() bool {
	if x != nil {
		return x.Udp
	}
	return false
}

type InitLoggerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *InitLoggerRequest) Reset() {
	*x = InitLoggerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitLoggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitLoggerRequest) ProtoMessage() {}

func (x *InitLoggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitLoggerRequest.ProtoReflect.Descriptor instead.
func (*InitLoggerRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{8}
}

func (x *InitLoggerRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{9}
}

var File_grpcproto_vpnserver_proto protoreflect.FileDescriptor

var file_grpcproto_vpnserver_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x70, 0x6e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x72, 0x70,
	0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41,
	0x77, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x33, 0x0a, 0x1b, 0x47, 0x65, 0x74,
	0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2d,
	0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x2e, 0x0a,
	0x14, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2c, 0x0a,
	0x12, 0x43, 0x6f, 0x75, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x47, 0x0a, 0x17, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x22, 0x32, 0x0a, 0x18, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x7f, 0x0a, 0x17, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x43, 0x6c, 0x6f, 0x61, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x48, 0x6f, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x48, 0x6f, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x64, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x75, 0x64, 0x70, 0x22, 0x27, 0x0a, 0x11, 0x49, 0x6e, 0x69,
	0x74, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x9e, 0x05, 0x0a, 0x03,
	0x56, 0x70, 0x6e, 0x12, 0x38, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x77, 0x67, 0x12,
	0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x41, 0x77, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2d, 0x0a,
	0x07, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x77, 0x67, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4f, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x26, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x4c, 0x61, 0x73, 0x74,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a,
	0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1e, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f,
	0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f,
	0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x70, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x10, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x3d, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f,
	0x75, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65,
	0x12, 0x5b, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41,
	0x6c, 0x69, 0x76, 0x65, 0x12, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x48, 0x0a,
	0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6c, 0x6f, 0x61, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x12, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x43, 0x6c, 0x6f, 0x61, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x35, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x70, 0x43,
	0x6c, 0x6f, 0x61, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3c,
	0x0a, 0x0a, 0x49, 0x6e, 0x69, 0x74, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x4c, 0x6f, 0x67,
	0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x15, 0x5a, 0x13,
	0x67, 0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcproto_vpnserver_proto_rawDescOnce sync.Once
	file_grpcproto_vpnserver_proto_rawDescData = file_grpcproto_vpnserver_proto_rawDesc
)

func file_grpcproto_vpnserver_proto_rawDescGZIP() []byte {
	file_grpcproto_vpnserver_proto_rawDescOnce.Do(func() {
		file_grpcproto_vpnserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcproto_vpnserver_proto_rawDescData)
	})
	return file_grpcproto_vpnserver_proto_rawDescData
}

var file_grpcproto_vpnserver_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_grpcproto_vpnserver_proto_goTypes = []interface{}{
	(*StartAwgRequest)(nil),             // 0: grpcproto.StartAwgRequest
	(*GetOutlineLastErrorResponse)(nil), // 1: grpcproto.GetOutlineLastErrorResponse
	(*StartOutlineRequest)(nil),         // 2: grpcproto.StartOutlineRequest
	(*StartOutlineResponse)(nil),        // 3: grpcproto.StartOutlineResponse
	(*CouldStartResponce)(nil),          // 4: grpcproto.CouldStartResponce
	(*CheckServerAliveRequest)(nil),     // 5: grpcproto.CheckServerAliveRequest
	(*CheckServerAliveResponce)(nil),    // 6: grpcproto.CheckServerAliveResponce
	(*StartCloakClientRequest)(nil),     // 7: grpcproto.StartCloakClientRequest
	(*InitLoggerRequest)(nil),           // 8: grpcproto.InitLoggerRequest
	(*Empty)(nil),                       // 9: grpcproto.Empty
}
var file_grpcproto_vpnserver_proto_depIdxs = []int32{
	0,  // 0: grpcproto.Vpn.StartAwg:input_type -> grpcproto.StartAwgRequest
	9,  // 1: grpcproto.Vpn.StopAwg:input_type -> grpcproto.Empty
	9,  // 2: grpcproto.Vpn.GetOutlineLastError:input_type -> grpcproto.Empty
	2,  // 3: grpcproto.Vpn.StartOutline:input_type -> grpcproto.StartOutlineRequest
	9,  // 4: grpcproto.Vpn.StopOutline:input_type -> grpcproto.Empty
	9,  // 5: grpcproto.Vpn.CouldStart:input_type -> grpcproto.Empty
	5,  // 6: grpcproto.Vpn.CheckServerAlive:input_type -> grpcproto.CheckServerAliveRequest
	7,  // 7: grpcproto.Vpn.StartCloakClient:input_type -> grpcproto.StartCloakClientRequest
	9,  // 8: grpcproto.Vpn.StopCloakClient:input_type -> grpcproto.Empty
	8,  // 9: grpcproto.Vpn.InitLogger:input_type -> grpcproto.InitLoggerRequest
	9,  // 10: grpcproto.Vpn.StartAwg:output_type -> grpcproto.Empty
	9,  // 11: grpcproto.Vpn.StopAwg:output_type -> grpcproto.Empty
	1,  // 12: grpcproto.Vpn.GetOutlineLastError:output_type -> grpcproto.GetOutlineLastErrorResponse
	3,  // 13: grpcproto.Vpn.StartOutline:output_type -> grpcproto.StartOutlineResponse
	9,  // 14: grpcproto.Vpn.StopOutline:output_type -> grpcproto.Empty
	4,  // 15: grpcproto.Vpn.CouldStart:output_type -> grpcproto.CouldStartResponce
	6,  // 16: grpcproto.Vpn.CheckServerAlive:output_type -> grpcproto.CheckServerAliveResponce
	9,  // 17: grpcproto.Vpn.StartCloakClient:output_type -> grpcproto.Empty
	9,  // 18: grpcproto.Vpn.StopCloakClient:output_type -> grpcproto.Empty
	9,  // 19: grpcproto.Vpn.InitLogger:output_type -> grpcproto.Empty
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_grpcproto_vpnserver_proto_init() }
func file_grpcproto_vpnserver_proto_init() {
	if File_grpcproto_vpnserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcproto_vpnserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartAwgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOutlineLastErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartOutlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartOutlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouldStartResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckServerAliveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckServerAliveResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartCloakClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitLoggerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcproto_vpnserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcproto_vpnserver_proto_goTypes,
		DependencyIndexes: file_grpcproto_vpnserver_proto_depIdxs,
		MessageInfos:      file_grpcproto_vpnserver_proto_msgTypes,
	}.Build()
	File_grpcproto_vpnserver_proto = out.File
	file_grpcproto_vpnserver_proto_rawDesc = nil
	file_grpcproto_vpnserver_proto_goTypes = nil
	file_grpcproto_vpnserver_proto_depIdxs = nil
}
