// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: grpcproto/vpnserver.proto

package grpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartAwgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        string                 `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAwgRequest) Reset() {
	*x = StartAwgRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAwgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAwgRequest) ProtoMessage() {}

func (x *StartAwgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAwgRequest.ProtoReflect.Descriptor instead.
func (*StartAwgRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{0}
}

func (x *StartAwgRequest) GetTunnel() string {
	if x != nil {
		return x.Tunnel
	}
	return ""
}

func (x *StartAwgRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type GetOutlineLastErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutlineLastErrorResponse) Reset() {
	*x = GetOutlineLastErrorResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutlineLastErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutlineLastErrorResponse) ProtoMessage() {}

func (x *GetOutlineLastErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutlineLastErrorResponse.ProtoReflect.Descriptor instead.
func (*GetOutlineLastErrorResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{1}
}

func (x *GetOutlineLastErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartOutlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOutlineRequest) Reset() {
	*x = StartOutlineRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOutlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOutlineRequest) ProtoMessage() {}

func (x *StartOutlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOutlineRequest.ProtoReflect.Descriptor instead.
func (*StartOutlineRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{2}
}

func (x *StartOutlineRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type StartOutlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOutlineResponse) Reset() {
	*x = StartOutlineResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOutlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOutlineResponse) ProtoMessage() {}

func (x *StartOutlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOutlineResponse.ProtoReflect.Descriptor instead.
func (*StartOutlineResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{3}
}

func (x *StartOutlineResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type CouldStartResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouldStartResponce) Reset() {
	*x = CouldStartResponce{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouldStartResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouldStartResponce) ProtoMessage() {}

func (x *CouldStartResponce) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouldStartResponce.ProtoReflect.Descriptor instead.
func (*CouldStartResponce) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{4}
}

func (x *CouldStartResponce) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type CheckServerAliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckServerAliveRequest) Reset() {
	*x = CheckServerAliveRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckServerAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckServerAliveRequest) ProtoMessage() {}

func (x *CheckServerAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckServerAliveRequest.ProtoReflect.Descriptor instead.
func (*CheckServerAliveRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{5}
}

func (x *CheckServerAliveRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CheckServerAliveRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CheckServerAliveResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckServerAliveResponce) Reset() {
	*x = CheckServerAliveResponce{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckServerAliveResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckServerAliveResponce) ProtoMessage() {}

func (x *CheckServerAliveResponce) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckServerAliveResponce.ProtoReflect.Descriptor instead.
func (*CheckServerAliveResponce) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{6}
}

func (x *CheckServerAliveResponce) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type StartCloakClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalHost     string                 `protobuf:"bytes,1,opt,name=localHost,proto3" json:"localHost,omitempty"`
	LocalPort     string                 `protobuf:"bytes,2,opt,name=localPort,proto3" json:"localPort,omitempty"`
	Config        string                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Udp           bool                   `protobuf:"varint,4,opt,name=udp,proto3" json:"udp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCloakClientRequest) Reset() {
	*x = StartCloakClientRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCloakClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCloakClientRequest) ProtoMessage() {}

func (x *StartCloakClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCloakClientRequest.ProtoReflect.Descriptor instead.
func (*StartCloakClientRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{7}
}

func (x *StartCloakClientRequest) GetLocalHost() string {
	if x != nil {
		return x.LocalHost
	}
	return ""
}

func (x *StartCloakClientRequest) GetLocalPort() string {
	if x != nil {
		return x.LocalPort
	}
	return ""
}

func (x *StartCloakClientRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StartCloakClientRequest) GetUdp() bool {
	if x != nil {
		return x.Udp
	}
	return false
}

type InitLoggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitLoggerRequest) Reset() {
	*x = InitLoggerRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitLoggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitLoggerRequest) ProtoMessage() {}

func (x *InitLoggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitLoggerRequest.ProtoReflect.Descriptor instead.
func (*InitLoggerRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{8}
}

func (x *InitLoggerRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SetGeoRoutingConfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidrs         string                 `protobuf:"bytes,1,opt,name=cidrs,proto3" json:"cidrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGeoRoutingConfRequest) Reset() {
	*x = SetGeoRoutingConfRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGeoRoutingConfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGeoRoutingConfRequest) ProtoMessage() {}

func (x *SetGeoRoutingConfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGeoRoutingConfRequest.ProtoReflect.Descriptor instead.
func (*SetGeoRoutingConfRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{9}
}

func (x *SetGeoRoutingConfRequest) GetCidrs() string {
	if x != nil {
		return x.Cidrs
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{10}
}

var File_grpcproto_vpnserver_proto protoreflect.FileDescriptor

const file_grpcproto_vpnserver_proto_rawDesc = "" +
	"\n" +
	"\x19grpcproto/vpnserver.proto\x12\tgrpcproto\"A\n" +
	"\x0fStartAwgRequest\x12\x16\n" +
	"\x06tunnel\x18\x01 \x01(\tR\x06tunnel\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\"3\n" +
	"\x1bGetOutlineLastErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"-\n" +
	"\x13StartOutlineRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\".\n" +
	"\x14StartOutlineResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\",\n" +
	"\x12CouldStartResponce\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"G\n" +
	"\x17CheckServerAliveRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"2\n" +
	"\x18CheckServerAliveResponce\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"\x7f\n" +
	"\x17StartCloakClientRequest\x12\x1c\n" +
	"\tlocalHost\x18\x01 \x01(\tR\tlocalHost\x12\x1c\n" +
	"\tlocalPort\x18\x02 \x01(\tR\tlocalPort\x12\x16\n" +
	"\x06config\x18\x03 \x01(\tR\x06config\x12\x10\n" +
	"\x03udp\x18\x04 \x01(\bR\x03udp\"'\n" +
	"\x11InitLoggerRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"0\n" +
	"\x18SetGeoRoutingConfRequest\x12\x14\n" +
	"\x05cidrs\x18\x01 \x01(\tR\x05cidrs\"\a\n" +
	"\x05Empty2\xa5\x06\n" +
	"\x03Vpn\x128\n" +
	"\bStartAwg\x12\x1a.grpcproto.StartAwgRequest\x1a\x10.grpcproto.Empty\x12-\n" +
	"\aStopAwg\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.Empty\x12O\n" +
	"\x13GetOutlineLastError\x12\x10.grpcproto.Empty\x1a&.grpcproto.GetOutlineLastErrorResponse\x12O\n" +
	"\fStartOutline\x12\x1e.grpcproto.StartOutlineRequest\x1a\x1f.grpcproto.StartOutlineResponse\x121\n" +
	"\vStopOutline\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.Empty\x12=\n" +
	"\n" +
	"CouldStart\x12\x10.grpcproto.Empty\x1a\x1d.grpcproto.CouldStartResponce\x12[\n" +
	"\x10CheckServerAlive\x12\".grpcproto.CheckServerAliveRequest\x1a#.grpcproto.CheckServerAliveResponce\x12H\n" +
	"\x10StartCloakClient\x12\".grpcproto.StartCloakClientRequest\x1a\x10.grpcproto.Empty\x125\n" +
	"\x0fStopCloakClient\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.Empty\x12<\n" +
	"\n" +
	"InitLogger\x12\x1c.grpcproto.InitLoggerRequest\x1a\x10.grpcproto.Empty\x12J\n" +
	"\x11SetGeoRoutingConf\x12#.grpcproto.SetGeoRoutingConfRequest\x1a\x10.grpcproto.Empty\x129\n" +
	"\x13ClearGeoRoutingConf\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.EmptyB\x15Z\x13go_client/grpcprotob\x06proto3"

var (
	file_grpcproto_vpnserver_proto_rawDescOnce sync.Once
	file_grpcproto_vpnserver_proto_rawDescData []byte
)

func file_grpcproto_vpnserver_proto_rawDescGZIP() []byte {
	file_grpcproto_vpnserver_proto_rawDescOnce.Do(func() {
		file_grpcproto_vpnserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcproto_vpnserver_proto_rawDesc), len(file_grpcproto_vpnserver_proto_rawDesc)))
	})
	return file_grpcproto_vpnserver_proto_rawDescData
}

var file_grpcproto_vpnserver_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_grpcproto_vpnserver_proto_goTypes = []any{
	(*StartAwgRequest)(nil),             // 0: grpcproto.StartAwgRequest
	(*GetOutlineLastErrorResponse)(nil), // 1: grpcproto.GetOutlineLastErrorResponse
	(*StartOutlineRequest)(nil),         // 2: grpcproto.StartOutlineRequest
	(*StartOutlineResponse)(nil),        // 3: grpcproto.StartOutlineResponse
	(*CouldStartResponce)(nil),          // 4: grpcproto.CouldStartResponce
	(*CheckServerAliveRequest)(nil),     // 5: grpcproto.CheckServerAliveRequest
	(*CheckServerAliveResponce)(nil),    // 6: grpcproto.CheckServerAliveResponce
	(*StartCloakClientRequest)(nil),     // 7: grpcproto.StartCloakClientRequest
	(*InitLoggerRequest)(nil),           // 8: grpcproto.InitLoggerRequest
	(*SetGeoRoutingConfRequest)(nil),    // 9: grpcproto.SetGeoRoutingConfRequest
	(*Empty)(nil),                       // 10: grpcproto.Empty
}
var file_grpcproto_vpnserver_proto_depIdxs = []int32{
	0,  // 0: grpcproto.Vpn.StartAwg:input_type -> grpcproto.StartAwgRequest
	10, // 1: grpcproto.Vpn.StopAwg:input_type -> grpcproto.Empty
	10, // 2: grpcproto.Vpn.GetOutlineLastError:input_type -> grpcproto.Empty
	2,  // 3: grpcproto.Vpn.StartOutline:input_type -> grpcproto.StartOutlineRequest
	10, // 4: grpcproto.Vpn.StopOutline:input_type -> grpcproto.Empty
	10, // 5: grpcproto.Vpn.CouldStart:input_type -> grpcproto.Empty
	5,  // 6: grpcproto.Vpn.CheckServerAlive:input_type -> grpcproto.CheckServerAliveRequest
	7,  // 7: grpcproto.Vpn.StartCloakClient:input_type -> grpcproto.StartCloakClientRequest
	10, // 8: grpcproto.Vpn.StopCloakClient:input_type -> grpcproto.Empty
	8,  // 9: grpcproto.Vpn.InitLogger:input_type -> grpcproto.InitLoggerRequest
	9,  // 10: grpcproto.Vpn.SetGeoRoutingConf:input_type -> grpcproto.SetGeoRoutingConfRequest
	10, // 11: grpcproto.Vpn.ClearGeoRoutingConf:input_type -> grpcproto.Empty
	10, // 12: grpcproto.Vpn.StartAwg:output_type -> grpcproto.Empty
	10, // 13: grpcproto.Vpn.StopAwg:output_type -> grpcproto.Empty
	1,  // 14: grpcproto.Vpn.GetOutlineLastError:output_type -> grpcproto.GetOutlineLastErrorResponse
	3,  // 15: grpcproto.Vpn.StartOutline:output_type -> grpcproto.StartOutlineResponse
	10, // 16: grpcproto.Vpn.StopOutline:output_type -> grpcproto.Empty
	4,  // 17: grpcproto.Vpn.CouldStart:output_type -> grpcproto.CouldStartResponce
	6,  // 18: grpcproto.Vpn.CheckServerAlive:output_type -> grpcproto.CheckServerAliveResponce
	10, // 19: grpcproto.Vpn.StartCloakClient:output_type -> grpcproto.Empty
	10, // 20: grpcproto.Vpn.StopCloakClient:output_type -> grpcproto.Empty
	10, // 21: grpcproto.Vpn.InitLogger:output_type -> grpcproto.Empty
	10, // 22: grpcproto.Vpn.SetGeoRoutingConf:output_type -> grpcproto.Empty
	10, // 23: grpcproto.Vpn.ClearGeoRoutingConf:output_type -> grpcproto.Empty
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_grpcproto_vpnserver_proto_init() }
func file_grpcproto_vpnserver_proto_init() {
	if File_grpcproto_vpnserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcproto_vpnserver_proto_rawDesc), len(file_grpcproto_vpnserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcproto_vpnserver_proto_goTypes,
		DependencyIndexes: file_grpcproto_vpnserver_proto_depIdxs,
		MessageInfos:      file_grpcproto_vpnserver_proto_msgTypes,
	}.Build()
	File_grpcproto_vpnserver_proto = out.File
	file_grpcproto_vpnserver_proto_goTypes = nil
	file_grpcproto_vpnserver_proto_depIdxs = nil
}
