# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: airportinfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61irportinfo.proto\"D\n\x07\x41irport\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0clatitude_deg\x18\x02 \x01(\x01\x12\x15\n\rlongitude_deg\x18\x03 \x01(\x01\")\n\x0b\x41irportList\x12\x1a\n\x08\x61irports\x18\x04 \x03(\x0b\x32\x08.Airport')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'airportinfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AIRPORT._serialized_start=21
  _AIRPORT._serialized_end=89
  _AIRPORTLIST._serialized_start=91
  _AIRPORTLIST._serialized_end=132
# @@protoc_insertion_point(module_scope)
