import app
import NetworkExtension
import Foundation

/// A NetworkExtension readiness and message-transport shell.
///
/// This class deliberately has no VPN product state, generation, configured
/// flag, or event sequence. Those values belong to Go SessionV2 in the
/// packet-tunnel process. The only state retained here is the private
/// readiness fence needed to deliver an authenticated provider message.
public final class VpnManagerImpl: NSObject {
    public static var dobbyBundleIdentifier = "vpn.dobby.app.tunnel"
    public static var dobbyName = "Dobby_VPN_4"
    private static let defaultServerAddress = "Dobby VPN"

    private let logs = NativeModuleHolder.logsRepository
    private let condition = NSCondition()
    private var vpnManager: NETunnelProviderManager?
    private var providerStatus: NEVPNStatus = .invalid
    private var observer: NSObjectProtocol?

    public init(connectionRepository: ConnectionStateRepository? = nil) {
        super.init()
        _ = connectionRepository // Compatibility for existing native-module construction.
        observer = NotificationCenter.default.addObserver(
            forName: .NEVPNStatusDidChange,
            object: nil,
            queue: nil
        ) { [weak self] notification in
            guard let self, let connection = notification.object as? NEVPNConnection else { return }
            self.condition.lock()
            guard let own = self.vpnManager?.connection, own === connection else {
                self.condition.unlock()
                return
            }
            self.providerStatus = connection.status
            self.condition.broadcast()
            self.condition.unlock()
            self.logs.writeLog(log: "[NEVPNStatusDidChange] provider status=\(self.statusName(connection.status)) raw=\(connection.status.rawValue)")
        }
    }

    deinit {
        if let observer { NotificationCenter.default.removeObserver(observer) }
    }

    /// Sends one exact authenticated command to the provider. A timeout or
    /// signed in-flight response is retried with the exact same bytes so the
    /// request ID remains idempotent. The inner Go payload is never rewritten.
    public func sendProviderMessage(_ messageData: Data) -> Data {
        guard !messageData.isEmpty, messageData.count <= IOSProviderCommand.maximumBytes else {
            return Self.transportFailure(IOSProviderMessageError.tooLarge.rawValue)
        }
        var budget = IOSProviderRetryBudget(start: monotonicNow())
        // Preference loading/saving, provider startup, and every transport
        // retry share one deadline. Readiness is part of this app operation;
        // it must not consume a second, independent 30-second allowance.
        guard ensureProviderReady(until: budget.deadline) else {
            return transportFailureResponse(
                for: messageData,
                code: monotonicNow() >= budget.deadline ? "SESSIONAPI_TIMEOUT" : "PLATFORM_FAILED"
            )
        }
        while let timeout = budget.nextAttemptTimeout(now: monotonicNow()) {
            if let response = sendOnce(messageData, timeout: timeout) {
                if !isRetryableProviderResponse(response, requestData: messageData) {
                    return response
                }
            }
            guard let delay = budget.nextRetryDelay(now: monotonicNow()) else {
                return transportFailureResponse(for: messageData, code: "SESSIONAPI_TIMEOUT")
            }
            logs.writeLog(log: "[provider-message] transport retry within aggregate \(Int(IOSProviderTiming.appMessageTimeout))s budget")
            Thread.sleep(forTimeInterval: delay)
        }
        return transportFailureResponse(for: messageData, code: "SESSIONAPI_TIMEOUT")
    }

    /// Stops only the control-mode provider. Callers invoke this after a
    /// successful Go Destroy response; a failed or timed-out destroy retains
    /// the provider and its mailbox for recovery.
    public func stopControlProvider() {
        condition.lock()
        let manager = vpnManager
        condition.unlock()
        manager?.connection.stopVPNTunnel()
    }

    public static func transportFailure(_ code: String) -> Data {
        Data("{\"ok\":false,\"error\":{\"code\":\"\(code)\"}}".utf8)
    }

    /// Failures generated by this transport shell are wrapped with the same
    /// request-bound HMAC as provider replies. That preserves the real typed
    /// readiness/timeout failure through IOSSessionShell instead of replacing
    /// it with a synthetic response-invalid error. If the command itself
    /// cannot be authenticated, the bare local failure is the only safe form.
    private func transportFailureResponse(for messageData: Data, code: String) -> Data {
        guard let secret = SharedKeychainSecretStore.shared.data(for: SharedKeychainSecretStore.sessionBridgeHMACKey),
              let command = try? IOSProviderCommand.decode(messageData, using: secret),
              let envelope = try? IOSProviderResponse(
                  requestID: command.requestID,
                  kind: .transport,
                  payload: Self.transportFailure(code)
              ),
              let encoded = try? envelope.encoded(using: secret) else {
            return Self.transportFailure(code)
        }
        return encoded
    }

    private func sendOnce(_ messageData: Data, timeout: TimeInterval) -> Data? {
        condition.lock()
        let session = vpnManager?.connection as? NETunnelProviderSession
        condition.unlock()
        guard let session else { return nil }
        let semaphore = DispatchSemaphore(value: 0)
        let responseLock = NSLock()
        var response: Data?
        session.sendProviderMessage(messageData) { value in
            responseLock.lock()
            response = value
            responseLock.unlock()
            semaphore.signal()
        }
        guard semaphore.wait(timeout: .now() + timeout) == .success else {
            return nil
        }
        responseLock.lock()
        defer { responseLock.unlock() }
        return response
    }

    private func monotonicNow() -> TimeInterval { ProcessInfo.processInfo.systemUptime }

    /// A signed provider timeout means the original fixed command may still
    /// be finishing inside Go; IN_FLIGHT means the same request is explicitly
    /// replayable. Retry the exact bytes/request ID until the provider returns
    /// its cached Go result or the bounded transport budget is exhausted.
    private func isRetryableProviderResponse(_ responseData: Data, requestData: Data) -> Bool {
        guard let secret = SharedKeychainSecretStore.shared.data(for: SharedKeychainSecretStore.sessionBridgeHMACKey),
              let command = try? IOSProviderCommand.decode(requestData, using: secret),
              let response = try? IOSProviderResponse.decode(
                  responseData,
                  expectedRequestID: command.requestID,
                  using: secret
              ),
              response.kind == .transport,
              let root = try? JSONSerialization.jsonObject(with: response.payload) as? [String: Any],
              root["ok"] as? Bool == false,
              let error = root["error"] as? [String: Any],
              let code = error["code"] as? String else { return false }
        return code == "SESSIONAPI_TIMEOUT" || code == "SESSIONAPI_IN_FLIGHT"
    }

    private func ensureProviderReady(until deadline: TimeInterval) -> Bool {
        if Thread.isMainThread {
            // KMP invokes this bridge on Dispatchers.Default. Refuse a main
            // thread wait rather than freezing the UI if a caller violates the
            // boundary.
            return false
        }
        // Once the saved-and-reloaded manager is connected, use that exact
        // bound object for subsequent commands. Re-saving preferences for
        // every Observe/Snapshot would add needless transition risk and
        // consume the aggregate command budget.
        condition.lock()
        if let current = vpnManager {
            providerStatus = current.connection.status
            if providerStatus == .connected {
                condition.unlock()
                return true
            }
        }
        condition.unlock()
        let loaded = DispatchSemaphore(value: 0)
        var loadedManager: NETunnelProviderManager?
        var loadError: Error?
        getOrCreateManager { value, error in
            loadedManager = value
            loadError = error
            loaded.signal()
        }
        guard let remaining = remaining(until: deadline),
              loaded.wait(timeout: .now() + remaining) == .success else {
            logs.writeLog(log: "[provider] timed out loading NetworkExtension preferences")
            return false
        }
        condition.lock()
        // getOrCreateManager returns the post-save reloaded object. Never
        // prefer an older in-memory manager after a provider-process restart.
        let current = loadedManager
        if let current {
            vpnManager = current
            providerStatus = current.connection.status
        }
        let status = current?.connection.status ?? .invalid
        condition.unlock()
        guard let current else { return false }
        if let loadError {
            logs.writeLog(log: "[provider] NetworkExtension preference save/load failed: \(loadError.localizedDescription)")
            return false
        }
        var observedStatus = status
        for _ in 0..<3 {
            if observedStatus == .connected { return true }
            if observedStatus == .disconnecting {
                guard let settled = waitForDisconnectToSettle(until: deadline) else { return false }
                observedStatus = settled
                continue
            }
            if observedStatus == .connecting || observedStatus == .reasserting {
                if waitForReady(until: deadline) { return true }
                observedStatus = current.connection.status
                continue
            }
            do {
                try current.connection.startVPNTunnel(options: nil)
            } catch {
                logs.writeLog(log: "[provider] control-mode start failed: \(error.localizedDescription)")
                return false
            }
            if waitForReady(until: deadline) { return true }
            observedStatus = current.connection.status
        }
        logs.writeLog(log: "[provider] control-mode provider did not reach connected state")
        return false
    }

    private func waitForReady(until monotonicDeadline: TimeInterval) -> Bool {
        condition.lock()
        defer { condition.unlock() }
        while providerStatus != .connected &&
            providerStatus != .disconnected &&
            providerStatus != .invalid &&
            providerStatus != .disconnecting &&
            monotonicNow() < monotonicDeadline {
            let deadline = Date().addingTimeInterval(min(0.1, remaining(until: monotonicDeadline) ?? 0))
            condition.wait(until: deadline)
            if let status = vpnManager?.connection.status { providerStatus = status }
        }
        return providerStatus == .connected
    }

    private func waitForDisconnectToSettle(until monotonicDeadline: TimeInterval) -> NEVPNStatus? {
        condition.lock()
        defer { condition.unlock() }
        while true {
            if let status = vpnManager?.connection.status { providerStatus = status }
            if providerStatus != .disconnecting { return providerStatus }
            guard let remaining = remaining(until: monotonicDeadline), remaining > 0 else { return nil }
            condition.wait(until: Date().addingTimeInterval(min(0.1, remaining)))
        }
    }

    private func remaining(until deadline: TimeInterval) -> TimeInterval? {
        let value = deadline - monotonicNow()
        return value > 0 ? value : nil
    }

    private func getOrCreateManager(completion: @escaping (NETunnelProviderManager?, Error?) -> Void) {
        NETunnelProviderManager.loadAllFromPreferences { [weak self] managers, error in
            guard let self else { completion(nil, error); return }
            if let error {
                self.logs.writeLog(log: "[provider] preference load failed: \(error.localizedDescription)")
                completion(nil, error)
                return
            }
            if let existing = managers?.first(where: { $0.localizedDescription == Self.dobbyName }) {
                self.applyProtocolDefaults(manager: existing)
                // Persist control-mode routing defaults before any start. An
                // in-memory fix is not sufficient because NetworkExtension
                // may reload the saved manager for the provider process.
                self.saveAndReload(existing, completion: completion)
                return
            }
            let created = self.makeManager()
            self.saveAndReload(created, completion: completion)
        }
    }

    /// NetworkExtension's save completion acknowledges persistence, but the
    /// manager object passed to it is not the authoritative object used by a
    /// subsequent start. Reload the saved preference and bind all state to
    /// that object before returning from the readiness fence.
    private func saveAndReload(
        _ manager: NETunnelProviderManager,
        completion: @escaping (NETunnelProviderManager?, Error?) -> Void
    ) {
        manager.saveToPreferences { [weak self] saveError in
            guard let self else { completion(nil, saveError); return }
            guard let saveError else {
                self.reloadSavedManager(completion: completion)
                return
            }
            self.logs.writeLog(log: "[provider] preference save failed: \(saveError.localizedDescription)")
            completion(nil, saveError)
        }
    }

    private func reloadSavedManager(
        completion: @escaping (NETunnelProviderManager?, Error?) -> Void
    ) {
        NETunnelProviderManager.loadAllFromPreferences { [weak self] managers, loadError in
            guard let self else { completion(nil, loadError); return }
            if let loadError {
                self.logs.writeLog(log: "[provider] preference reload failed: \(loadError.localizedDescription)")
                completion(nil, loadError)
                return
            }
            guard let reloaded = managers?.first(where: { $0.localizedDescription == Self.dobbyName }) else {
                let missing = NSError(
                    domain: "PacketTunnelProvider.preferences",
                    code: -8,
                    userInfo: [NSLocalizedDescriptionKey: "saved DobbyVPN NetworkExtension manager was not returned by reload"]
                )
                self.logs.writeLog(log: "[provider] preference reload did not return the saved DobbyVPN manager")
                completion(nil, missing)
                return
            }
            self.condition.lock()
            self.vpnManager = reloaded
            self.providerStatus = reloaded.connection.status
            self.condition.broadcast()
            self.condition.unlock()
            completion(reloaded, nil)
        }
    }

    private func makeManager() -> NETunnelProviderManager {
        let manager = NETunnelProviderManager()
        manager.localizedDescription = Self.dobbyName
        manager.protocolConfiguration = makeDefaultProtocol()
        manager.isEnabled = true
        return manager
    }

    private func applyProtocolDefaults(manager: NETunnelProviderManager) {
        let proto = (manager.protocolConfiguration as? NETunnelProviderProtocol) ?? NETunnelProviderProtocol()
        applyProtocolDefaults(proto)
        manager.protocolConfiguration = proto
        manager.isEnabled = true
    }

    private func makeDefaultProtocol() -> NETunnelProviderProtocol {
        let proto = NETunnelProviderProtocol()
        proto.providerConfiguration = ["mode": "control"]
        applyProtocolDefaults(proto)
        return proto
    }

    private func applyProtocolDefaults(_ proto: NETunnelProviderProtocol) {
        proto.providerBundleIdentifier = Self.dobbyBundleIdentifier
        proto.serverAddress = Self.defaultServerAddress
        proto.providerConfiguration = ["mode": "control"]
        // Control mode must not claim all traffic before Go owns a generation
        // and the provider applies settings at its AcquireTunnel callback.
        proto.includeAllNetworks = false
        proto.excludeLocalNetworks = false
        proto.enforceRoutes = false
        if #available(iOS 16.4, *) {
            proto.excludeCellularServices = false
            proto.excludeAPNs = false
        }
        if #available(iOS 17.4, *) { proto.excludeDeviceCommunication = false }
    }

    private func statusName(_ status: NEVPNStatus) -> String {
        switch status {
        case .invalid: return "invalid"
        case .disconnected: return "disconnected"
        case .connecting: return "connecting"
        case .connected: return "connected"
        case .reasserting: return "reasserting"
        case .disconnecting: return "disconnecting"
        @unknown default: return "unknown"
        }
    }
}
