// Objective-C API for talking to go_client/ios_exports Go package.
//   gobind -lang=objc go_client/ios_exports
//
// File is generated by gobind. Do not edit.

#ifndef __Cloak_outline_H__
#define __Cloak_outline_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Cloak_outlineOutlineDevice;

@interface Cloak_outlineOutlineDevice : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)transportConfig;
// skipped field OutlineDevice.IPDevice with unsupported type: github.com/Jigsaw-Code/outline-sdk/network.IPDevice

- (BOOL)close:(NSError* _Nullable* _Nullable)error;
// skipped method OutlineDevice.GetServerIP with unsupported parameter or return types

- (long)mtu;
- (NSData* _Nullable)read:(NSError* _Nullable* _Nullable)error;
- (BOOL)refresh:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)buf ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT NSString* _Nonnull Cloak_outlineAwgGetConfig(int32_t tunnelHandle);

FOUNDATION_EXPORT int32_t Cloak_outlineAwgGetSocketV4(int32_t tunnelHandle);

FOUNDATION_EXPORT int32_t Cloak_outlineAwgGetSocketV6(int32_t tunnelHandle);

FOUNDATION_EXPORT void Cloak_outlineAwgTurnOff(int32_t tunnelHandle);

FOUNDATION_EXPORT int32_t Cloak_outlineAwgTurnOn(NSString* _Nullable interfaceName, int32_t tunFd, NSString* _Nullable settings);

FOUNDATION_EXPORT NSString* _Nonnull Cloak_outlineAwgVersion(void);

FOUNDATION_EXPORT NSString* _Nonnull Cloak_outlineLogMemStats(void);

FOUNDATION_EXPORT Cloak_outlineOutlineDevice* _Nullable Cloak_outlineNewOutlineDevice(NSString* _Nullable transportConfig, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void Cloak_outlineStartCloakClient(NSString* _Nullable localHost, NSString* _Nullable localPort, NSString* _Nullable config, BOOL udp);

FOUNDATION_EXPORT void Cloak_outlineStartHealthCheck(long period, BOOL sendMetrics);

FOUNDATION_EXPORT NSString* _Nonnull Cloak_outlineStatus(void);

FOUNDATION_EXPORT void Cloak_outlineStopCloakClient(void);

FOUNDATION_EXPORT void Cloak_outlineStopHealthCheck(void);

FOUNDATION_EXPORT BOOL Cloak_outlineTcpPing(NSString* _Nullable address, int32_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL Cloak_outlineUrlTest(NSString* _Nullable url, long standard, int32_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

#endif
