
// Objective-C API for talking to the following Go packages
//
//	go_client/ios_exports
//
// File is generated by gomobile bind. Do not edit.
#ifndef __MyLibrary_FRAMEWORK_H__
#define __MyLibrary_FRAMEWORK_H__

#include "Cloak_outline.objc.h"
#include "Universe.objc.h"

#endif
