// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: grpcproto/vpnserver.proto

package grpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

type GetTrustTunnelLastErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

var file_grpcproto_trusttunnel_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)

func (x *GetTrustTunnelLastErrorResponse) Reset() {
	*x = GetTrustTunnelLastErrorResponse{}
	mi := &file_grpcproto_trusttunnel_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrustTunnelLastErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrustTunnelLastErrorResponse) ProtoMessage() {}

func (x *GetTrustTunnelLastErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_trusttunnel_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrustTunnelLastErrorResponse.ProtoReflect.Descriptor instead.
func (*GetTrustTunnelLastErrorResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{14}
}

func (x *GetTrustTunnelLastErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartTrustTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTrustTunnelRequest) Reset() {
	*x = StartTrustTunnelRequest{}
	mi := &file_grpcproto_trusttunnel_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTrustTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrustTunnelRequest) ProtoMessage() {}

func (x *StartTrustTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_trusttunnel_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrustTunnelRequest.ProtoReflect.Descriptor instead.
func (*StartTrustTunnelRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{15}
}

func (x *StartTrustTunnelRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type StartTrustTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTrustTunnelResponse) Reset() {
	*x = StartTrustTunnelResponse{}
	mi := &file_grpcproto_trusttunnel_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTrustTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrustTunnelResponse) ProtoMessage() {}

func (x *StartTrustTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_trusttunnel_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrustTunnelResponse.ProtoReflect.Descriptor instead.
func (*StartTrustTunnelResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{16}
}

func (x *StartTrustTunnelResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}
