// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: grpcproto/vpnserver.proto

package grpcproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Vpn_StartAwg_FullMethodName            = "/grpcproto.Vpn/StartAwg"
	Vpn_StopAwg_FullMethodName             = "/grpcproto.Vpn/StopAwg"
	Vpn_GetOutlineLastError_FullMethodName = "/grpcproto.Vpn/GetOutlineLastError"
	Vpn_StartOutline_FullMethodName        = "/grpcproto.Vpn/StartOutline"
	Vpn_StopOutline_FullMethodName         = "/grpcproto.Vpn/StopOutline"
	Vpn_CouldStart_FullMethodName          = "/grpcproto.Vpn/CouldStart"
	Vpn_CheckServerAlive_FullMethodName    = "/grpcproto.Vpn/CheckServerAlive"
	Vpn_StartCloakClient_FullMethodName    = "/grpcproto.Vpn/StartCloakClient"
	Vpn_StopCloakClient_FullMethodName     = "/grpcproto.Vpn/StopCloakClient"
	Vpn_InitLogger_FullMethodName          = "/grpcproto.Vpn/InitLogger"
	Vpn_SetGeoRoutingConf_FullMethodName   = "/grpcproto.Vpn/SetGeoRoutingConf"
	Vpn_ClearGeoRoutingConf_FullMethodName = "/grpcproto.Vpn/ClearGeoRoutingConf"
	Vpn_NetCheck_FullMethodName            = "/grpcproto.Vpn/NetCheck"
	Vpn_CancelNetCheck_FullMethodName      = "/grpcproto.Vpn/CancelNetCheck"
)

// VpnClient is the client API for Vpn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VpnClient interface {
	// awg.go
	StartAwg(ctx context.Context, in *StartAwgRequest, opts ...grpc.CallOption) (*Empty, error)
	StopAwg(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// outline.go
	GetOutlineLastError(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetOutlineLastErrorResponse, error)
	StartOutline(ctx context.Context, in *StartOutlineRequest, opts ...grpc.CallOption) (*StartOutlineResponse, error)
	StopOutline(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// health_check.go
	CouldStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CouldStartResponce, error)
	CheckServerAlive(ctx context.Context, in *CheckServerAliveRequest, opts ...grpc.CallOption) (*CheckServerAliveResponce, error)
	// cloak.go
	StartCloakClient(ctx context.Context, in *StartCloakClientRequest, opts ...grpc.CallOption) (*Empty, error)
	StopCloakClient(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// logger.go
	InitLogger(ctx context.Context, in *InitLoggerRequest, opts ...grpc.CallOption) (*Empty, error)
	// georouting.go
	SetGeoRoutingConf(ctx context.Context, in *SetGeoRoutingConfRequest, opts ...grpc.CallOption) (*Empty, error)
	ClearGeoRoutingConf(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// netcheck.go
	NetCheck(ctx context.Context, in *NetCheckRequest, opts ...grpc.CallOption) (*NetCheckResponse, error)
	CancelNetCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type vpnClient struct {
	cc grpc.ClientConnInterface
}

func NewVpnClient(cc grpc.ClientConnInterface) VpnClient {
	return &vpnClient{cc}
}

func (c *vpnClient) StartAwg(ctx context.Context, in *StartAwgRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Vpn_StartAwg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) StopAwg(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Vpn_StopAwg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) GetOutlineLastError(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetOutlineLastErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOutlineLastErrorResponse)
	err := c.cc.Invoke(ctx, Vpn_GetOutlineLastError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) StartOutline(ctx context.Context, in *StartOutlineRequest, opts ...grpc.CallOption) (*StartOutlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOutlineResponse)
	err := c.cc.Invoke(ctx, Vpn_StartOutline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) StopOutline(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Vpn_StopOutline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) CouldStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CouldStartResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CouldStartResponce)
	err := c.cc.Invoke(ctx, Vpn_CouldStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) CheckServerAlive(ctx context.Context, in *CheckServerAliveRequest, opts ...grpc.CallOption) (*CheckServerAliveResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckServerAliveResponce)
	err := c.cc.Invoke(ctx, Vpn_CheckServerAlive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) StartCloakClient(ctx context.Context, in *StartCloakClientRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Vpn_StartCloakClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) StopCloakClient(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Vpn_StopCloakClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) InitLogger(ctx context.Context, in *InitLoggerRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Vpn_InitLogger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) SetGeoRoutingConf(ctx context.Context, in *SetGeoRoutingConfRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Vpn_SetGeoRoutingConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) ClearGeoRoutingConf(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Vpn_ClearGeoRoutingConf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) NetCheck(ctx context.Context, in *NetCheckRequest, opts ...grpc.CallOption) (*NetCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetCheckResponse)
	err := c.cc.Invoke(ctx, Vpn_NetCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) CancelNetCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Vpn_CancelNetCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VpnServer is the server API for Vpn service.
// All implementations must embed UnimplementedVpnServer
// for forward compatibility.
type VpnServer interface {
	// awg.go
	StartAwg(context.Context, *StartAwgRequest) (*Empty, error)
	StopAwg(context.Context, *Empty) (*Empty, error)
	// outline.go
	GetOutlineLastError(context.Context, *Empty) (*GetOutlineLastErrorResponse, error)
	StartOutline(context.Context, *StartOutlineRequest) (*StartOutlineResponse, error)
	StopOutline(context.Context, *Empty) (*Empty, error)
	// health_check.go
	CouldStart(context.Context, *Empty) (*CouldStartResponce, error)
	CheckServerAlive(context.Context, *CheckServerAliveRequest) (*CheckServerAliveResponce, error)
	// cloak.go
	StartCloakClient(context.Context, *StartCloakClientRequest) (*Empty, error)
	StopCloakClient(context.Context, *Empty) (*Empty, error)
	// logger.go
	InitLogger(context.Context, *InitLoggerRequest) (*Empty, error)
	// georouting.go
	SetGeoRoutingConf(context.Context, *SetGeoRoutingConfRequest) (*Empty, error)
	ClearGeoRoutingConf(context.Context, *Empty) (*Empty, error)
	// netcheck.go
	NetCheck(context.Context, *NetCheckRequest) (*NetCheckResponse, error)
	CancelNetCheck(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedVpnServer()
}

// UnimplementedVpnServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVpnServer struct{}

func (UnimplementedVpnServer) StartAwg(context.Context, *StartAwgRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAwg not implemented")
}
func (UnimplementedVpnServer) StopAwg(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAwg not implemented")
}
func (UnimplementedVpnServer) GetOutlineLastError(context.Context, *Empty) (*GetOutlineLastErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOutlineLastError not implemented")
}
func (UnimplementedVpnServer) StartOutline(context.Context, *StartOutlineRequest) (*StartOutlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartOutline not implemented")
}
func (UnimplementedVpnServer) StopOutline(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopOutline not implemented")
}
func (UnimplementedVpnServer) CouldStart(context.Context, *Empty) (*CouldStartResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouldStart not implemented")
}
func (UnimplementedVpnServer) CheckServerAlive(context.Context, *CheckServerAliveRequest) (*CheckServerAliveResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckServerAlive not implemented")
}
func (UnimplementedVpnServer) StartCloakClient(context.Context, *StartCloakClientRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCloakClient not implemented")
}
func (UnimplementedVpnServer) StopCloakClient(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopCloakClient not implemented")
}
func (UnimplementedVpnServer) InitLogger(context.Context, *InitLoggerRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitLogger not implemented")
}
func (UnimplementedVpnServer) SetGeoRoutingConf(context.Context, *SetGeoRoutingConfRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGeoRoutingConf not implemented")
}
func (UnimplementedVpnServer) ClearGeoRoutingConf(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearGeoRoutingConf not implemented")
}
func (UnimplementedVpnServer) NetCheck(context.Context, *NetCheckRequest) (*NetCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetCheck not implemented")
}
func (UnimplementedVpnServer) CancelNetCheck(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelNetCheck not implemented")
}
func (UnimplementedVpnServer) mustEmbedUnimplementedVpnServer() {}
func (UnimplementedVpnServer) testEmbeddedByValue()             {}

// UnsafeVpnServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VpnServer will
// result in compilation errors.
type UnsafeVpnServer interface {
	mustEmbedUnimplementedVpnServer()
}

func RegisterVpnServer(s grpc.ServiceRegistrar, srv VpnServer) {
	// If the following call pancis, it indicates UnimplementedVpnServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Vpn_ServiceDesc, srv)
}

func _Vpn_StartAwg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAwgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).StartAwg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_StartAwg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).StartAwg(ctx, req.(*StartAwgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_StopAwg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).StopAwg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_StopAwg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).StopAwg(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_GetOutlineLastError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).GetOutlineLastError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_GetOutlineLastError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).GetOutlineLastError(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_StartOutline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartOutlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).StartOutline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_StartOutline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).StartOutline(ctx, req.(*StartOutlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_StopOutline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).StopOutline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_StopOutline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).StopOutline(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_CouldStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).CouldStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_CouldStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).CouldStart(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_CheckServerAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckServerAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).CheckServerAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_CheckServerAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).CheckServerAlive(ctx, req.(*CheckServerAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_StartCloakClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCloakClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).StartCloakClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_StartCloakClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).StartCloakClient(ctx, req.(*StartCloakClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_StopCloakClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).StopCloakClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_StopCloakClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).StopCloakClient(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_InitLogger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitLoggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).InitLogger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_InitLogger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).InitLogger(ctx, req.(*InitLoggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_SetGeoRoutingConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGeoRoutingConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).SetGeoRoutingConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_SetGeoRoutingConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).SetGeoRoutingConf(ctx, req.(*SetGeoRoutingConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_ClearGeoRoutingConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).ClearGeoRoutingConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_ClearGeoRoutingConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).ClearGeoRoutingConf(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_NetCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).NetCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_NetCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).NetCheck(ctx, req.(*NetCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_CancelNetCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).CancelNetCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_CancelNetCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).CancelNetCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Vpn_ServiceDesc is the grpc.ServiceDesc for Vpn service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vpn_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcproto.Vpn",
	HandlerType: (*VpnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartAwg",
			Handler:    _Vpn_StartAwg_Handler,
		},
		{
			MethodName: "StopAwg",
			Handler:    _Vpn_StopAwg_Handler,
		},
		{
			MethodName: "GetOutlineLastError",
			Handler:    _Vpn_GetOutlineLastError_Handler,
		},
		{
			MethodName: "StartOutline",
			Handler:    _Vpn_StartOutline_Handler,
		},
		{
			MethodName: "StopOutline",
			Handler:    _Vpn_StopOutline_Handler,
		},
		{
			MethodName: "CouldStart",
			Handler:    _Vpn_CouldStart_Handler,
		},
		{
			MethodName: "CheckServerAlive",
			Handler:    _Vpn_CheckServerAlive_Handler,
		},
		{
			MethodName: "StartCloakClient",
			Handler:    _Vpn_StartCloakClient_Handler,
		},
		{
			MethodName: "StopCloakClient",
			Handler:    _Vpn_StopCloakClient_Handler,
		},
		{
			MethodName: "InitLogger",
			Handler:    _Vpn_InitLogger_Handler,
		},
		{
			MethodName: "SetGeoRoutingConf",
			Handler:    _Vpn_SetGeoRoutingConf_Handler,
		},
		{
			MethodName: "ClearGeoRoutingConf",
			Handler:    _Vpn_ClearGeoRoutingConf_Handler,
		},
		{
			MethodName: "NetCheck",
			Handler:    _Vpn_NetCheck_Handler,
		},
		{
			MethodName: "CancelNetCheck",
			Handler:    _Vpn_CancelNetCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcproto/vpnserver.proto",
}
