// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: grpcproto/vpnserver.proto

package grpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartAwgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAwgRequest) Reset() {
	*x = StartAwgRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAwgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAwgRequest) ProtoMessage() {}

func (x *StartAwgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAwgRequest.ProtoReflect.Descriptor instead.
func (*StartAwgRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{0}
}

func (x *StartAwgRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type GetOutlineLastErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutlineLastErrorResponse) Reset() {
	*x = GetOutlineLastErrorResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutlineLastErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutlineLastErrorResponse) ProtoMessage() {}

func (x *GetOutlineLastErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutlineLastErrorResponse.ProtoReflect.Descriptor instead.
func (*GetOutlineLastErrorResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{1}
}

func (x *GetOutlineLastErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartOutlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOutlineRequest) Reset() {
	*x = StartOutlineRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOutlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOutlineRequest) ProtoMessage() {}

func (x *StartOutlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOutlineRequest.ProtoReflect.Descriptor instead.
func (*StartOutlineRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{2}
}

func (x *StartOutlineRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type StartOutlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOutlineResponse) Reset() {
	*x = StartOutlineResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOutlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOutlineResponse) ProtoMessage() {}

func (x *StartOutlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOutlineResponse.ProtoReflect.Descriptor instead.
func (*StartOutlineResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{3}
}

func (x *StartOutlineResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type GetXrayLastErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetXrayLastErrorResponse) Reset() {
	*x = GetXrayLastErrorResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetXrayLastErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXrayLastErrorResponse) ProtoMessage() {}

func (x *GetXrayLastErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXrayLastErrorResponse.ProtoReflect.Descriptor instead.
func (*GetXrayLastErrorResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{4}
}

func (x *GetXrayLastErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartXrayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartXrayRequest) Reset() {
	*x = StartXrayRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartXrayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartXrayRequest) ProtoMessage() {}

func (x *StartXrayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartXrayRequest.ProtoReflect.Descriptor instead.
func (*StartXrayRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{5}
}

func (x *StartXrayRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type StartXrayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartXrayResponse) Reset() {
	*x = StartXrayResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartXrayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartXrayResponse) ProtoMessage() {}

func (x *StartXrayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartXrayResponse.ProtoReflect.Descriptor instead.
func (*StartXrayResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{6}
}

func (x *StartXrayResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type CouldStartResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouldStartResponce) Reset() {
	*x = CouldStartResponce{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouldStartResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouldStartResponce) ProtoMessage() {}

func (x *CouldStartResponce) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouldStartResponce.ProtoReflect.Descriptor instead.
func (*CouldStartResponce) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{7}
}

func (x *CouldStartResponce) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetConnectionStateResponce struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConnectionState int32                  `protobuf:"varint,1,opt,name=connectionState,proto3" json:"connectionState,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConnectionStateResponce) Reset() {
	*x = GetConnectionStateResponce{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStateResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStateResponce) ProtoMessage() {}

func (x *GetConnectionStateResponce) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStateResponce.ProtoReflect.Descriptor instead.
func (*GetConnectionStateResponce) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{8}
}

func (x *GetConnectionStateResponce) GetConnectionState() int32 {
	if x != nil {
		return x.ConnectionState
	}
	return 0
}

type StartCloakClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalHost     string                 `protobuf:"bytes,1,opt,name=localHost,proto3" json:"localHost,omitempty"`
	LocalPort     string                 `protobuf:"bytes,2,opt,name=localPort,proto3" json:"localPort,omitempty"`
	Config        string                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Udp           bool                   `protobuf:"varint,4,opt,name=udp,proto3" json:"udp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCloakClientRequest) Reset() {
	*x = StartCloakClientRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCloakClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCloakClientRequest) ProtoMessage() {}

func (x *StartCloakClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCloakClientRequest.ProtoReflect.Descriptor instead.
func (*StartCloakClientRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{9}
}

func (x *StartCloakClientRequest) GetLocalHost() string {
	if x != nil {
		return x.LocalHost
	}
	return ""
}

func (x *StartCloakClientRequest) GetLocalPort() string {
	if x != nil {
		return x.LocalPort
	}
	return ""
}

func (x *StartCloakClientRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StartCloakClientRequest) GetUdp() bool {
	if x != nil {
		return x.Udp
	}
	return false
}

type InitLoggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitLoggerRequest) Reset() {
	*x = InitLoggerRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitLoggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitLoggerRequest) ProtoMessage() {}

func (x *InitLoggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitLoggerRequest.ProtoReflect.Descriptor instead.
func (*InitLoggerRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{10}
}

func (x *InitLoggerRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type InitTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitTelemetryRequest) Reset() {
	*x = InitTelemetryRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitTelemetryRequest) ProtoMessage() {}

func (x *InitTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitTelemetryRequest.ProtoReflect.Descriptor instead.
func (*InitTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{11}
}

func (x *InitTelemetryRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *InitTelemetryRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SetGeoRoutingConfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidrs         string                 `protobuf:"bytes,1,opt,name=cidrs,proto3" json:"cidrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGeoRoutingConfRequest) Reset() {
	*x = SetGeoRoutingConfRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGeoRoutingConfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGeoRoutingConfRequest) ProtoMessage() {}

func (x *SetGeoRoutingConfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGeoRoutingConfRequest.ProtoReflect.Descriptor instead.
func (*SetGeoRoutingConfRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{12}
}

func (x *SetGeoRoutingConfRequest) GetCidrs() string {
	if x != nil {
		return x.Cidrs
	}
	return ""
}

type NetCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=configPath,proto3" json:"configPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetCheckRequest) Reset() {
	*x = NetCheckRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetCheckRequest) ProtoMessage() {}

func (x *NetCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetCheckRequest.ProtoReflect.Descriptor instead.
func (*NetCheckRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{13}
}

func (x *NetCheckRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type NetCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetCheckResponse) Reset() {
	*x = NetCheckResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetCheckResponse) ProtoMessage() {}

func (x *NetCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetCheckResponse.ProtoReflect.Descriptor instead.
func (*NetCheckResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{14}
}

func (x *NetCheckResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetupTelemetryAttributesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupTelemetryAttributesRequest) Reset() {
	*x = SetupTelemetryAttributesRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupTelemetryAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupTelemetryAttributesRequest) ProtoMessage() {}

func (x *SetupTelemetryAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupTelemetryAttributesRequest.ProtoReflect.Descriptor instead.
func (*SetupTelemetryAttributesRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{15}
}

func (x *SetupTelemetryAttributesRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type GetTrustTunnelLastErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrustTunnelLastErrorResponse) Reset() {
	*x = GetTrustTunnelLastErrorResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrustTunnelLastErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrustTunnelLastErrorResponse) ProtoMessage() {}

func (x *GetTrustTunnelLastErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrustTunnelLastErrorResponse.ProtoReflect.Descriptor instead.
func (*GetTrustTunnelLastErrorResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{16}
}

func (x *GetTrustTunnelLastErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartTrustTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTrustTunnelRequest) Reset() {
	*x = StartTrustTunnelRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTrustTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrustTunnelRequest) ProtoMessage() {}

func (x *StartTrustTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrustTunnelRequest.ProtoReflect.Descriptor instead.
func (*StartTrustTunnelRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{17}
}

func (x *StartTrustTunnelRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type StartTrustTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTrustTunnelResponse) Reset() {
	*x = StartTrustTunnelResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTrustTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrustTunnelResponse) ProtoMessage() {}

func (x *StartTrustTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrustTunnelResponse.ProtoReflect.Descriptor instead.
func (*StartTrustTunnelResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{18}
}

func (x *StartTrustTunnelResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type CheckServerAliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckServerAliveRequest) Reset() {
	*x = CheckServerAliveRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckServerAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckServerAliveRequest) ProtoMessage() {}

func (x *CheckServerAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckServerAliveRequest.ProtoReflect.Descriptor instead.
func (*CheckServerAliveRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{19}
}

func (x *CheckServerAliveRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CheckServerAliveRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CheckServerAliveResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckServerAliveResponce) Reset() {
	*x = CheckServerAliveResponce{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckServerAliveResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckServerAliveResponce) ProtoMessage() {}

func (x *CheckServerAliveResponce) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckServerAliveResponce.ProtoReflect.Descriptor instead.
func (*CheckServerAliveResponce) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{20}
}

func (x *CheckServerAliveResponce) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{21}
}

var File_grpcproto_vpnserver_proto protoreflect.FileDescriptor

const file_grpcproto_vpnserver_proto_rawDesc = "" +
	"\n" +
	"\x19grpcproto/vpnserver.proto\x12\tgrpcproto\")\n" +
	"\x0fStartAwgRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"3\n" +
	"\x1bGetOutlineLastErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"-\n" +
	"\x13StartOutlineRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\".\n" +
	"\x14StartOutlineResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"0\n" +
	"\x18GetXrayLastErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"*\n" +
	"\x10StartXrayRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"+\n" +
	"\x11StartXrayResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\",\n" +
	"\x12CouldStartResponce\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"F\n" +
	"\x1aGetConnectionStateResponce\x12(\n" +
	"\x0fconnectionState\x18\x01 \x01(\x05R\x0fconnectionState\"\x7f\n" +
	"\x17StartCloakClientRequest\x12\x1c\n" +
	"\tlocalHost\x18\x01 \x01(\tR\tlocalHost\x12\x1c\n" +
	"\tlocalPort\x18\x02 \x01(\tR\tlocalPort\x12\x16\n" +
	"\x06config\x18\x03 \x01(\tR\x06config\x12\x10\n" +
	"\x03udp\x18\x04 \x01(\bR\x03udp\"'\n" +
	"\x11InitLoggerRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"H\n" +
	"\x14InitTelemetryRequest\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"0\n" +
	"\x18SetGeoRoutingConfRequest\x12\x14\n" +
	"\x05cidrs\x18\x01 \x01(\tR\x05cidrs\"1\n" +
	"\x0fNetCheckRequest\x12\x1e\n" +
	"\n" +
	"configPath\x18\x01 \x01(\tR\n" +
	"configPath\"(\n" +
	"\x10NetCheckResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"9\n" +
	"\x1fSetupTelemetryAttributesRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"7\n" +
	"\x1fGetTrustTunnelLastErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"1\n" +
	"\x17StartTrustTunnelRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"2\n" +
	"\x18StartTrustTunnelResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"G\n" +
	"\x17CheckServerAliveRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"2\n" +
	"\x18CheckServerAliveResponce\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"\a\n" +
	"\x05Empty2\x9d\r\n" +
	"\x03Vpn\x128\n" +
	"\bStartAwg\x12\x1a.grpcproto.StartAwgRequest\x1a\x10.grpcproto.Empty\x12-\n" +
	"\aStopAwg\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.Empty\x12O\n" +
	"\x13GetOutlineLastError\x12\x10.grpcproto.Empty\x1a&.grpcproto.GetOutlineLastErrorResponse\x12O\n" +
	"\fStartOutline\x12\x1e.grpcproto.StartOutlineRequest\x1a\x1f.grpcproto.StartOutlineResponse\x121\n" +
	"\vStopOutline\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.Empty\x12I\n" +
	"\x10GetXrayLastError\x12\x10.grpcproto.Empty\x1a#.grpcproto.GetXrayLastErrorResponse\x12F\n" +
	"\tStartXray\x12\x1b.grpcproto.StartXrayRequest\x1a\x1c.grpcproto.StartXrayResponse\x12.\n" +
	"\bStopXray\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.Empty\x12W\n" +
	"\x17GetTrustTunnelLastError\x12\x10.grpcproto.Empty\x1a*.grpcproto.GetTrustTunnelLastErrorResponse\x12[\n" +
	"\x10StartTrustTunnel\x12\".grpcproto.StartTrustTunnelRequest\x1a#.grpcproto.StartTrustTunnelResponse\x125\n" +
	"\x0fStopTrustTunnel\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.Empty\x12=\n" +
	"\n" +
	"CouldStart\x12\x10.grpcproto.Empty\x1a\x1d.grpcproto.CouldStartResponce\x12M\n" +
	"\x12GetConnectionState\x12\x10.grpcproto.Empty\x1a%.grpcproto.GetConnectionStateResponce\x125\n" +
	"\x0fInitHealthCheck\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.Empty\x126\n" +
	"\x10StartHealthCheck\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.Empty\x125\n" +
	"\x0fStopHealthCheck\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.Empty\x12[\n" +
	"\x10CheckServerAlive\x12\".grpcproto.CheckServerAliveRequest\x1a#.grpcproto.CheckServerAliveResponce\x12H\n" +
	"\x10StartCloakClient\x12\".grpcproto.StartCloakClientRequest\x1a\x10.grpcproto.Empty\x125\n" +
	"\x0fStopCloakClient\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.Empty\x12<\n" +
	"\n" +
	"InitLogger\x12\x1c.grpcproto.InitLoggerRequest\x1a\x10.grpcproto.Empty\x12B\n" +
	"\rInitTelemetry\x12\x1f.grpcproto.InitTelemetryRequest\x1a\x10.grpcproto.Empty\x123\n" +
	"\rStopTelemetry\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.Empty\x12X\n" +
	"\x18SetupTelemetryAttributes\x12*.grpcproto.SetupTelemetryAttributesRequest\x1a\x10.grpcproto.Empty\x12J\n" +
	"\x11SetGeoRoutingConf\x12#.grpcproto.SetGeoRoutingConfRequest\x1a\x10.grpcproto.Empty\x129\n" +
	"\x13ClearGeoRoutingConf\x12\x10.grpcproto.Empty\x1a\x10.grpcproto.EmptyB\x15Z\x13go_module/grpcprotob\x06proto3"

var (
	file_grpcproto_vpnserver_proto_rawDescOnce sync.Once
	file_grpcproto_vpnserver_proto_rawDescData []byte
)

func file_grpcproto_vpnserver_proto_rawDescGZIP() []byte {
	file_grpcproto_vpnserver_proto_rawDescOnce.Do(func() {
		file_grpcproto_vpnserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcproto_vpnserver_proto_rawDesc), len(file_grpcproto_vpnserver_proto_rawDesc)))
	})
	return file_grpcproto_vpnserver_proto_rawDescData
}

var file_grpcproto_vpnserver_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_grpcproto_vpnserver_proto_goTypes = []any{
	(*StartAwgRequest)(nil),                 // 0: grpcproto.StartAwgRequest
	(*GetOutlineLastErrorResponse)(nil),     // 1: grpcproto.GetOutlineLastErrorResponse
	(*StartOutlineRequest)(nil),             // 2: grpcproto.StartOutlineRequest
	(*StartOutlineResponse)(nil),            // 3: grpcproto.StartOutlineResponse
	(*GetXrayLastErrorResponse)(nil),        // 4: grpcproto.GetXrayLastErrorResponse
	(*StartXrayRequest)(nil),                // 5: grpcproto.StartXrayRequest
	(*StartXrayResponse)(nil),               // 6: grpcproto.StartXrayResponse
	(*CouldStartResponce)(nil),              // 7: grpcproto.CouldStartResponce
	(*GetConnectionStateResponce)(nil),      // 8: grpcproto.GetConnectionStateResponce
	(*StartCloakClientRequest)(nil),         // 9: grpcproto.StartCloakClientRequest
	(*InitLoggerRequest)(nil),               // 10: grpcproto.InitLoggerRequest
	(*InitTelemetryRequest)(nil),            // 11: grpcproto.InitTelemetryRequest
	(*SetGeoRoutingConfRequest)(nil),        // 12: grpcproto.SetGeoRoutingConfRequest
	(*NetCheckRequest)(nil),                 // 13: grpcproto.NetCheckRequest
	(*NetCheckResponse)(nil),                // 14: grpcproto.NetCheckResponse
	(*SetupTelemetryAttributesRequest)(nil), // 15: grpcproto.SetupTelemetryAttributesRequest
	(*GetTrustTunnelLastErrorResponse)(nil), // 16: grpcproto.GetTrustTunnelLastErrorResponse
	(*StartTrustTunnelRequest)(nil),         // 17: grpcproto.StartTrustTunnelRequest
	(*StartTrustTunnelResponse)(nil),        // 18: grpcproto.StartTrustTunnelResponse
	(*CheckServerAliveRequest)(nil),         // 19: grpcproto.CheckServerAliveRequest
	(*CheckServerAliveResponce)(nil),        // 20: grpcproto.CheckServerAliveResponce
	(*Empty)(nil),                           // 21: grpcproto.Empty
}
var file_grpcproto_vpnserver_proto_depIdxs = []int32{
	0,  // 0: grpcproto.Vpn.StartAwg:input_type -> grpcproto.StartAwgRequest
	21, // 1: grpcproto.Vpn.StopAwg:input_type -> grpcproto.Empty
	21, // 2: grpcproto.Vpn.GetOutlineLastError:input_type -> grpcproto.Empty
	2,  // 3: grpcproto.Vpn.StartOutline:input_type -> grpcproto.StartOutlineRequest
	21, // 4: grpcproto.Vpn.StopOutline:input_type -> grpcproto.Empty
	21, // 5: grpcproto.Vpn.GetXrayLastError:input_type -> grpcproto.Empty
	5,  // 6: grpcproto.Vpn.StartXray:input_type -> grpcproto.StartXrayRequest
	21, // 7: grpcproto.Vpn.StopXray:input_type -> grpcproto.Empty
	21, // 8: grpcproto.Vpn.GetTrustTunnelLastError:input_type -> grpcproto.Empty
	17, // 9: grpcproto.Vpn.StartTrustTunnel:input_type -> grpcproto.StartTrustTunnelRequest
	21, // 10: grpcproto.Vpn.StopTrustTunnel:input_type -> grpcproto.Empty
	21, // 11: grpcproto.Vpn.CouldStart:input_type -> grpcproto.Empty
	21, // 12: grpcproto.Vpn.GetConnectionState:input_type -> grpcproto.Empty
	21, // 13: grpcproto.Vpn.InitHealthCheck:input_type -> grpcproto.Empty
	21, // 14: grpcproto.Vpn.StartHealthCheck:input_type -> grpcproto.Empty
	21, // 15: grpcproto.Vpn.StopHealthCheck:input_type -> grpcproto.Empty
	19, // 16: grpcproto.Vpn.CheckServerAlive:input_type -> grpcproto.CheckServerAliveRequest
	9,  // 17: grpcproto.Vpn.StartCloakClient:input_type -> grpcproto.StartCloakClientRequest
	21, // 18: grpcproto.Vpn.StopCloakClient:input_type -> grpcproto.Empty
	10, // 19: grpcproto.Vpn.InitLogger:input_type -> grpcproto.InitLoggerRequest
	11, // 20: grpcproto.Vpn.InitTelemetry:input_type -> grpcproto.InitTelemetryRequest
	21, // 21: grpcproto.Vpn.StopTelemetry:input_type -> grpcproto.Empty
	15, // 22: grpcproto.Vpn.SetupTelemetryAttributes:input_type -> grpcproto.SetupTelemetryAttributesRequest
	12, // 23: grpcproto.Vpn.SetGeoRoutingConf:input_type -> grpcproto.SetGeoRoutingConfRequest
	21, // 24: grpcproto.Vpn.ClearGeoRoutingConf:input_type -> grpcproto.Empty
	21, // 25: grpcproto.Vpn.StartAwg:output_type -> grpcproto.Empty
	21, // 26: grpcproto.Vpn.StopAwg:output_type -> grpcproto.Empty
	1,  // 27: grpcproto.Vpn.GetOutlineLastError:output_type -> grpcproto.GetOutlineLastErrorResponse
	3,  // 28: grpcproto.Vpn.StartOutline:output_type -> grpcproto.StartOutlineResponse
	21, // 29: grpcproto.Vpn.StopOutline:output_type -> grpcproto.Empty
	4,  // 30: grpcproto.Vpn.GetXrayLastError:output_type -> grpcproto.GetXrayLastErrorResponse
	6,  // 31: grpcproto.Vpn.StartXray:output_type -> grpcproto.StartXrayResponse
	21, // 32: grpcproto.Vpn.StopXray:output_type -> grpcproto.Empty
	16, // 33: grpcproto.Vpn.GetTrustTunnelLastError:output_type -> grpcproto.GetTrustTunnelLastErrorResponse
	18, // 34: grpcproto.Vpn.StartTrustTunnel:output_type -> grpcproto.StartTrustTunnelResponse
	21, // 35: grpcproto.Vpn.StopTrustTunnel:output_type -> grpcproto.Empty
	7,  // 36: grpcproto.Vpn.CouldStart:output_type -> grpcproto.CouldStartResponce
	8,  // 37: grpcproto.Vpn.GetConnectionState:output_type -> grpcproto.GetConnectionStateResponce
	21, // 38: grpcproto.Vpn.InitHealthCheck:output_type -> grpcproto.Empty
	21, // 39: grpcproto.Vpn.StartHealthCheck:output_type -> grpcproto.Empty
	21, // 40: grpcproto.Vpn.StopHealthCheck:output_type -> grpcproto.Empty
	20, // 41: grpcproto.Vpn.CheckServerAlive:output_type -> grpcproto.CheckServerAliveResponce
	21, // 42: grpcproto.Vpn.StartCloakClient:output_type -> grpcproto.Empty
	21, // 43: grpcproto.Vpn.StopCloakClient:output_type -> grpcproto.Empty
	21, // 44: grpcproto.Vpn.InitLogger:output_type -> grpcproto.Empty
	21, // 45: grpcproto.Vpn.InitTelemetry:output_type -> grpcproto.Empty
	21, // 46: grpcproto.Vpn.StopTelemetry:output_type -> grpcproto.Empty
	21, // 47: grpcproto.Vpn.SetupTelemetryAttributes:output_type -> grpcproto.Empty
	21, // 48: grpcproto.Vpn.SetGeoRoutingConf:output_type -> grpcproto.Empty
	21, // 49: grpcproto.Vpn.ClearGeoRoutingConf:output_type -> grpcproto.Empty
	25, // [25:50] is the sub-list for method output_type
	0,  // [0:25] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_grpcproto_vpnserver_proto_init() }
func file_grpcproto_vpnserver_proto_init() {
	if File_grpcproto_vpnserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcproto_vpnserver_proto_rawDesc), len(file_grpcproto_vpnserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcproto_vpnserver_proto_goTypes,
		DependencyIndexes: file_grpcproto_vpnserver_proto_depIdxs,
		MessageInfos:      file_grpcproto_vpnserver_proto_msgTypes,
	}.Build()
	File_grpcproto_vpnserver_proto = out.File
	file_grpcproto_vpnserver_proto_goTypes = nil
	file_grpcproto_vpnserver_proto_depIdxs = nil
}
