// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.35.1
// source: grpcproto/vpnserver.proto

package grpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOutlineLastErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetOutlineLastErrorResponse) Reset() {
	*x = GetOutlineLastErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOutlineLastErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutlineLastErrorResponse) ProtoMessage() {}

func (x *GetOutlineLastErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutlineLastErrorResponse.ProtoReflect.Descriptor instead.
func (*GetOutlineLastErrorResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{0}
}

func (x *GetOutlineLastErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartOutlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *StartOutlineRequest) Reset() {
	*x = StartOutlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartOutlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOutlineRequest) ProtoMessage() {}

func (x *StartOutlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOutlineRequest.ProtoReflect.Descriptor instead.
func (*StartOutlineRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{1}
}

func (x *StartOutlineRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type StartOutlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *StartOutlineResponse) Reset() {
	*x = StartOutlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartOutlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOutlineResponse) ProtoMessage() {}

func (x *StartOutlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOutlineResponse.ProtoReflect.Descriptor instead.
func (*StartOutlineResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{2}
}

func (x *StartOutlineResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type GetXrayLastErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetXrayLastErrorResponse) Reset() {
	*x = GetXrayLastErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXrayLastErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXrayLastErrorResponse) ProtoMessage() {}

func (x *GetXrayLastErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXrayLastErrorResponse.ProtoReflect.Descriptor instead.
func (*GetXrayLastErrorResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{3}
}

func (x *GetXrayLastErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartXrayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *StartXrayRequest) Reset() {
	*x = StartXrayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartXrayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartXrayRequest) ProtoMessage() {}

func (x *StartXrayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartXrayRequest.ProtoReflect.Descriptor instead.
func (*StartXrayRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{4}
}

func (x *StartXrayRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type StartXrayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *StartXrayResponse) Reset() {
	*x = StartXrayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartXrayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartXrayResponse) ProtoMessage() {}

func (x *StartXrayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartXrayResponse.ProtoReflect.Descriptor instead.
func (*StartXrayResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{5}
}

func (x *StartXrayResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type CouldStartResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CouldStartResponce) Reset() {
	*x = CouldStartResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouldStartResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouldStartResponce) ProtoMessage() {}

func (x *CouldStartResponce) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouldStartResponce.ProtoReflect.Descriptor instead.
func (*CouldStartResponce) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{6}
}

func (x *CouldStartResponce) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetConnectionStateResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnectionState int32 `protobuf:"varint,1,opt,name=connectionState,proto3" json:"connectionState,omitempty"`
}

func (x *GetConnectionStateResponce) Reset() {
	*x = GetConnectionStateResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConnectionStateResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStateResponce) ProtoMessage() {}

func (x *GetConnectionStateResponce) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStateResponce.ProtoReflect.Descriptor instead.
func (*GetConnectionStateResponce) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{7}
}

func (x *GetConnectionStateResponce) GetConnectionState() int32 {
	if x != nil {
		return x.ConnectionState
	}
	return 0
}

type MeasureTunnelProbeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeoutMillis int64 `protobuf:"varint,1,opt,name=timeoutMillis,proto3" json:"timeoutMillis,omitempty"`
}

func (x *MeasureTunnelProbeRequest) Reset() {
	*x = MeasureTunnelProbeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasureTunnelProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureTunnelProbeRequest) ProtoMessage() {}

func (x *MeasureTunnelProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureTunnelProbeRequest.ProtoReflect.Descriptor instead.
func (*MeasureTunnelProbeRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{8}
}

func (x *MeasureTunnelProbeRequest) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

type MeasureTunnelProbeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AverageLatencyMillis int64 `protobuf:"varint,1,opt,name=averageLatencyMillis,proto3" json:"averageLatencyMillis,omitempty"`
}

func (x *MeasureTunnelProbeResponse) Reset() {
	*x = MeasureTunnelProbeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasureTunnelProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureTunnelProbeResponse) ProtoMessage() {}

func (x *MeasureTunnelProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureTunnelProbeResponse.ProtoReflect.Descriptor instead.
func (*MeasureTunnelProbeResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{9}
}

func (x *MeasureTunnelProbeResponse) GetAverageLatencyMillis() int64 {
	if x != nil {
		return x.AverageLatencyMillis
	}
	return 0
}

type StartCloakClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalHost string `protobuf:"bytes,1,opt,name=localHost,proto3" json:"localHost,omitempty"`
	LocalPort string `protobuf:"bytes,2,opt,name=localPort,proto3" json:"localPort,omitempty"`
	Config    string `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Udp       bool   `protobuf:"varint,4,opt,name=udp,proto3" json:"udp,omitempty"`
}

func (x *StartCloakClientRequest) Reset() {
	*x = StartCloakClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCloakClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCloakClientRequest) ProtoMessage() {}

func (x *StartCloakClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCloakClientRequest.ProtoReflect.Descriptor instead.
func (*StartCloakClientRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{10}
}

func (x *StartCloakClientRequest) GetLocalHost() string {
	if x != nil {
		return x.LocalHost
	}
	return ""
}

func (x *StartCloakClientRequest) GetLocalPort() string {
	if x != nil {
		return x.LocalPort
	}
	return ""
}

func (x *StartCloakClientRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StartCloakClientRequest) GetUdp() bool {
	if x != nil {
		return x.Udp
	}
	return false
}

type InitLoggerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *InitLoggerRequest) Reset() {
	*x = InitLoggerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitLoggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitLoggerRequest) ProtoMessage() {}

func (x *InitLoggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitLoggerRequest.ProtoReflect.Descriptor instead.
func (*InitLoggerRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{11}
}

func (x *InitLoggerRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type InitTelemetryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *InitTelemetryRequest) Reset() {
	*x = InitTelemetryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitTelemetryRequest) ProtoMessage() {}

func (x *InitTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitTelemetryRequest.ProtoReflect.Descriptor instead.
func (*InitTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{12}
}

func (x *InitTelemetryRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *InitTelemetryRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SetGeoRoutingConfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cidrs string `protobuf:"bytes,1,opt,name=cidrs,proto3" json:"cidrs,omitempty"`
}

func (x *SetGeoRoutingConfRequest) Reset() {
	*x = SetGeoRoutingConfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetGeoRoutingConfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGeoRoutingConfRequest) ProtoMessage() {}

func (x *SetGeoRoutingConfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGeoRoutingConfRequest.ProtoReflect.Descriptor instead.
func (*SetGeoRoutingConfRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{13}
}

func (x *SetGeoRoutingConfRequest) GetCidrs() string {
	if x != nil {
		return x.Cidrs
	}
	return ""
}

type NetCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigPath string `protobuf:"bytes,1,opt,name=configPath,proto3" json:"configPath,omitempty"`
}

func (x *NetCheckRequest) Reset() {
	*x = NetCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetCheckRequest) ProtoMessage() {}

func (x *NetCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetCheckRequest.ProtoReflect.Descriptor instead.
func (*NetCheckRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{14}
}

func (x *NetCheckRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type NetCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *NetCheckResponse) Reset() {
	*x = NetCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetCheckResponse) ProtoMessage() {}

func (x *NetCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetCheckResponse.ProtoReflect.Descriptor instead.
func (*NetCheckResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{15}
}

func (x *NetCheckResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetupTelemetryAttributesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *SetupTelemetryAttributesRequest) Reset() {
	*x = SetupTelemetryAttributesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupTelemetryAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupTelemetryAttributesRequest) ProtoMessage() {}

func (x *SetupTelemetryAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupTelemetryAttributesRequest.ProtoReflect.Descriptor instead.
func (*SetupTelemetryAttributesRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{16}
}

func (x *SetupTelemetryAttributesRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type GetTrustTunnelLastErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetTrustTunnelLastErrorResponse) Reset() {
	*x = GetTrustTunnelLastErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrustTunnelLastErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrustTunnelLastErrorResponse) ProtoMessage() {}

func (x *GetTrustTunnelLastErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrustTunnelLastErrorResponse.ProtoReflect.Descriptor instead.
func (*GetTrustTunnelLastErrorResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{17}
}

func (x *GetTrustTunnelLastErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartTrustTunnelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *StartTrustTunnelRequest) Reset() {
	*x = StartTrustTunnelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartTrustTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrustTunnelRequest) ProtoMessage() {}

func (x *StartTrustTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrustTunnelRequest.ProtoReflect.Descriptor instead.
func (*StartTrustTunnelRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{18}
}

func (x *StartTrustTunnelRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type StartTrustTunnelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *StartTrustTunnelResponse) Reset() {
	*x = StartTrustTunnelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartTrustTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrustTunnelResponse) ProtoMessage() {}

func (x *StartTrustTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrustTunnelResponse.ProtoReflect.Descriptor instead.
func (*StartTrustTunnelResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{19}
}

func (x *StartTrustTunnelResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type CheckServerAliveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port    int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *CheckServerAliveRequest) Reset() {
	*x = CheckServerAliveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckServerAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckServerAliveRequest) ProtoMessage() {}

func (x *CheckServerAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckServerAliveRequest.ProtoReflect.Descriptor instead.
func (*CheckServerAliveRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{20}
}

func (x *CheckServerAliveRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CheckServerAliveRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CheckServerAliveResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CheckServerAliveResponce) Reset() {
	*x = CheckServerAliveResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckServerAliveResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckServerAliveResponce) ProtoMessage() {}

func (x *CheckServerAliveResponce) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckServerAliveResponce.ProtoReflect.Descriptor instead.
func (*CheckServerAliveResponce) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{21}
}

func (x *CheckServerAliveResponce) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type SetDNSCacheEntriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries string `protobuf:"bytes,1,opt,name=entries,proto3" json:"entries,omitempty"`
	Source  string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *SetDNSCacheEntriesRequest) Reset() {
	*x = SetDNSCacheEntriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDNSCacheEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDNSCacheEntriesRequest) ProtoMessage() {}

func (x *SetDNSCacheEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDNSCacheEntriesRequest.ProtoReflect.Descriptor instead.
func (*SetDNSCacheEntriesRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{22}
}

func (x *SetDNSCacheEntriesRequest) GetEntries() string {
	if x != nil {
		return x.Entries
	}
	return ""
}

func (x *SetDNSCacheEntriesRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type SetDNSCacheEntriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CachedCount int32 `protobuf:"varint,1,opt,name=cachedCount,proto3" json:"cachedCount,omitempty"`
}

func (x *SetDNSCacheEntriesResponse) Reset() {
	*x = SetDNSCacheEntriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDNSCacheEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDNSCacheEntriesResponse) ProtoMessage() {}

func (x *SetDNSCacheEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDNSCacheEntriesResponse.ProtoReflect.Descriptor instead.
func (*SetDNSCacheEntriesResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{23}
}

func (x *SetDNSCacheEntriesResponse) GetCachedCount() int32 {
	if x != nil {
		return x.CachedCount
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproto_vpnserver_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{24}
}

var File_grpcproto_vpnserver_proto protoreflect.FileDescriptor

var file_grpcproto_vpnserver_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x70, 0x6e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x72, 0x70,
	0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74,
	0x6c, 0x69, 0x6e, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2d, 0x0a, 0x13, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x2e, 0x0a, 0x14, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x30, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x58, 0x72, 0x61, 0x79, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2a, 0x0a, 0x10,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x58, 0x72, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x2b, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x58, 0x72, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2c, 0x0a, 0x12, 0x43, 0x6f, 0x75, 0x6c, 0x64, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x46, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63,
	0x65, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x41, 0x0a, 0x19, 0x4d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x62,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0d, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x22, 0x50,
	0x0a, 0x1a, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50,
	0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x14,
	0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x69,
	0x6c, 0x6c, 0x69, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14, 0x61, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73,
	0x22, 0x7f, 0x0a, 0x17, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6c, 0x6f, 0x61, 0x6b, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x64, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x75, 0x64,
	0x70, 0x22, 0x27, 0x0a, 0x11, 0x49, 0x6e, 0x69, 0x74, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x48, 0x0a, 0x14, 0x49, 0x6e,
	0x69, 0x74, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x30, 0x0a, 0x18, 0x53, 0x65, 0x74, 0x47, 0x65, 0x6f, 0x52, 0x6f,
	0x75, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x69, 0x64, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x69, 0x64, 0x72, 0x73, 0x22, 0x31, 0x0a, 0x0f, 0x4e, 0x65, 0x74, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x61, 0x74, 0x68, 0x22, 0x28, 0x0a, 0x10, 0x4e, 0x65, 0x74,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x39, 0x0a, 0x1f, 0x53, 0x65, 0x74, 0x75, 0x70, 0x54, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x37,
	0x0a, 0x1f, 0x47, 0x65, 0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0x4c, 0x61, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x31, 0x0a, 0x17, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x72, 0x75, 0x73, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x32, 0x0a, 0x18, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x47,
	0x0a, 0x17, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x6c, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x32, 0x0a, 0x18, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4d, 0x0a, 0x19, 0x53,
	0x65, 0x74, 0x44, 0x4e, 0x53, 0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x3e, 0x0a, 0x1a, 0x53, 0x65,
	0x74, 0x44, 0x4e, 0x53, 0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x32, 0xc3, 0x0e, 0x0a, 0x03, 0x56, 0x70, 0x6e, 0x12, 0x4f, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x26, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0c,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1e, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x75,
	0x74, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x75,
	0x74, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x0b, 0x53, 0x74, 0x6f, 0x70, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x10, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x49, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x58, 0x72, 0x61, 0x79, 0x4c, 0x61, 0x73, 0x74, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x23, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x72, 0x61, 0x79, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x09, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x58, 0x72, 0x61, 0x79, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x58, 0x72, 0x61, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x58, 0x72, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x53, 0x74, 0x6f, 0x70, 0x58, 0x72, 0x61, 0x79, 0x12,
	0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x57, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x54,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x2a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x72, 0x75, 0x73, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x4c, 0x61, 0x73, 0x74, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x10,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x72, 0x75, 0x73, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0f, 0x53, 0x74, 0x6f,
	0x70, 0x54, 0x72, 0x75, 0x73, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x10, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x3d, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x75,
	0x6c, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x4d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x35,
	0x0a, 0x0f, 0x49, 0x6e, 0x69, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x36, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x35, 0x0a,
	0x0f, 0x53, 0x74, 0x6f, 0x70, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x5b, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63,
	0x65, 0x12, 0x75, 0x0a, 0x26, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x54, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4c, 0x61,
	0x74, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x12, 0x24, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x54,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x62, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x43, 0x6c, 0x6f, 0x61, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6c,
	0x6f, 0x61, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x35, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x70, 0x43, 0x6c, 0x6f, 0x61, 0x6b, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3c, 0x0a, 0x0a, 0x49, 0x6e, 0x69,
	0x74, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x42, 0x0a, 0x0d, 0x49, 0x6e, 0x69, 0x74, 0x54,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x33, 0x0a, 0x0d, 0x53,
	0x74, 0x6f, 0x70, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x10, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x58, 0x0a, 0x18, 0x53, 0x65, 0x74, 0x75, 0x70, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x2a, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x54, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4a, 0x0a, 0x11, 0x53, 0x65,
	0x74, 0x47, 0x65, 0x6f, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x12,
	0x23, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x47,
	0x65, 0x6f, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x39, 0x0a, 0x13, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x47,
	0x65, 0x6f, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x10, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x33, 0x0a, 0x0d, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x44, 0x4e, 0x53, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x61, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x44, 0x4e, 0x53,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x24, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x4e, 0x53, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x74, 0x44, 0x4e, 0x53, 0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x67, 0x6f, 0x5f,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcproto_vpnserver_proto_rawDescOnce sync.Once
	file_grpcproto_vpnserver_proto_rawDescData = file_grpcproto_vpnserver_proto_rawDesc
)

func file_grpcproto_vpnserver_proto_rawDescGZIP() []byte {
	file_grpcproto_vpnserver_proto_rawDescOnce.Do(func() {
		file_grpcproto_vpnserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcproto_vpnserver_proto_rawDescData)
	})
	return file_grpcproto_vpnserver_proto_rawDescData
}

var file_grpcproto_vpnserver_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_grpcproto_vpnserver_proto_goTypes = []interface{}{
	(*GetOutlineLastErrorResponse)(nil),     // 0: grpcproto.GetOutlineLastErrorResponse
	(*StartOutlineRequest)(nil),             // 1: grpcproto.StartOutlineRequest
	(*StartOutlineResponse)(nil),            // 2: grpcproto.StartOutlineResponse
	(*GetXrayLastErrorResponse)(nil),        // 3: grpcproto.GetXrayLastErrorResponse
	(*StartXrayRequest)(nil),                // 4: grpcproto.StartXrayRequest
	(*StartXrayResponse)(nil),               // 5: grpcproto.StartXrayResponse
	(*CouldStartResponce)(nil),              // 6: grpcproto.CouldStartResponce
	(*GetConnectionStateResponce)(nil),      // 7: grpcproto.GetConnectionStateResponce
	(*MeasureTunnelProbeRequest)(nil),       // 8: grpcproto.MeasureTunnelProbeRequest
	(*MeasureTunnelProbeResponse)(nil),      // 9: grpcproto.MeasureTunnelProbeResponse
	(*StartCloakClientRequest)(nil),         // 10: grpcproto.StartCloakClientRequest
	(*InitLoggerRequest)(nil),               // 11: grpcproto.InitLoggerRequest
	(*InitTelemetryRequest)(nil),            // 12: grpcproto.InitTelemetryRequest
	(*SetGeoRoutingConfRequest)(nil),        // 13: grpcproto.SetGeoRoutingConfRequest
	(*NetCheckRequest)(nil),                 // 14: grpcproto.NetCheckRequest
	(*NetCheckResponse)(nil),                // 15: grpcproto.NetCheckResponse
	(*SetupTelemetryAttributesRequest)(nil), // 16: grpcproto.SetupTelemetryAttributesRequest
	(*GetTrustTunnelLastErrorResponse)(nil), // 17: grpcproto.GetTrustTunnelLastErrorResponse
	(*StartTrustTunnelRequest)(nil),         // 18: grpcproto.StartTrustTunnelRequest
	(*StartTrustTunnelResponse)(nil),        // 19: grpcproto.StartTrustTunnelResponse
	(*CheckServerAliveRequest)(nil),         // 20: grpcproto.CheckServerAliveRequest
	(*CheckServerAliveResponce)(nil),        // 21: grpcproto.CheckServerAliveResponce
	(*SetDNSCacheEntriesRequest)(nil),       // 22: grpcproto.SetDNSCacheEntriesRequest
	(*SetDNSCacheEntriesResponse)(nil),      // 23: grpcproto.SetDNSCacheEntriesResponse
	(*Empty)(nil),                           // 24: grpcproto.Empty
}
var file_grpcproto_vpnserver_proto_depIdxs = []int32{
	24, // 0: grpcproto.Vpn.GetOutlineLastError:input_type -> grpcproto.Empty
	1,  // 1: grpcproto.Vpn.StartOutline:input_type -> grpcproto.StartOutlineRequest
	24, // 2: grpcproto.Vpn.StopOutline:input_type -> grpcproto.Empty
	24, // 3: grpcproto.Vpn.GetXrayLastError:input_type -> grpcproto.Empty
	4,  // 4: grpcproto.Vpn.StartXray:input_type -> grpcproto.StartXrayRequest
	24, // 5: grpcproto.Vpn.StopXray:input_type -> grpcproto.Empty
	24, // 6: grpcproto.Vpn.GetTrustTunnelLastError:input_type -> grpcproto.Empty
	18, // 7: grpcproto.Vpn.StartTrustTunnel:input_type -> grpcproto.StartTrustTunnelRequest
	24, // 8: grpcproto.Vpn.StopTrustTunnel:input_type -> grpcproto.Empty
	24, // 9: grpcproto.Vpn.CouldStart:input_type -> grpcproto.Empty
	24, // 10: grpcproto.Vpn.GetConnectionState:input_type -> grpcproto.Empty
	24, // 11: grpcproto.Vpn.InitHealthCheck:input_type -> grpcproto.Empty
	24, // 12: grpcproto.Vpn.StartHealthCheck:input_type -> grpcproto.Empty
	24, // 13: grpcproto.Vpn.StopHealthCheck:input_type -> grpcproto.Empty
	20, // 14: grpcproto.Vpn.CheckServerAlive:input_type -> grpcproto.CheckServerAliveRequest
	8,  // 15: grpcproto.Vpn.MeasureTunnelProbeAverageLatencyMillis:input_type -> grpcproto.MeasureTunnelProbeRequest
	10, // 16: grpcproto.Vpn.StartCloakClient:input_type -> grpcproto.StartCloakClientRequest
	24, // 17: grpcproto.Vpn.StopCloakClient:input_type -> grpcproto.Empty
	11, // 18: grpcproto.Vpn.InitLogger:input_type -> grpcproto.InitLoggerRequest
	12, // 19: grpcproto.Vpn.InitTelemetry:input_type -> grpcproto.InitTelemetryRequest
	24, // 20: grpcproto.Vpn.StopTelemetry:input_type -> grpcproto.Empty
	16, // 21: grpcproto.Vpn.SetupTelemetryAttributes:input_type -> grpcproto.SetupTelemetryAttributesRequest
	13, // 22: grpcproto.Vpn.SetGeoRoutingConf:input_type -> grpcproto.SetGeoRoutingConfRequest
	24, // 23: grpcproto.Vpn.ClearGeoRoutingConf:input_type -> grpcproto.Empty
	24, // 24: grpcproto.Vpn.ClearDNSCache:input_type -> grpcproto.Empty
	22, // 25: grpcproto.Vpn.SetDNSCacheEntries:input_type -> grpcproto.SetDNSCacheEntriesRequest
	0,  // 26: grpcproto.Vpn.GetOutlineLastError:output_type -> grpcproto.GetOutlineLastErrorResponse
	2,  // 27: grpcproto.Vpn.StartOutline:output_type -> grpcproto.StartOutlineResponse
	24, // 28: grpcproto.Vpn.StopOutline:output_type -> grpcproto.Empty
	3,  // 29: grpcproto.Vpn.GetXrayLastError:output_type -> grpcproto.GetXrayLastErrorResponse
	5,  // 30: grpcproto.Vpn.StartXray:output_type -> grpcproto.StartXrayResponse
	24, // 31: grpcproto.Vpn.StopXray:output_type -> grpcproto.Empty
	17, // 32: grpcproto.Vpn.GetTrustTunnelLastError:output_type -> grpcproto.GetTrustTunnelLastErrorResponse
	19, // 33: grpcproto.Vpn.StartTrustTunnel:output_type -> grpcproto.StartTrustTunnelResponse
	24, // 34: grpcproto.Vpn.StopTrustTunnel:output_type -> grpcproto.Empty
	6,  // 35: grpcproto.Vpn.CouldStart:output_type -> grpcproto.CouldStartResponce
	7,  // 36: grpcproto.Vpn.GetConnectionState:output_type -> grpcproto.GetConnectionStateResponce
	24, // 37: grpcproto.Vpn.InitHealthCheck:output_type -> grpcproto.Empty
	24, // 38: grpcproto.Vpn.StartHealthCheck:output_type -> grpcproto.Empty
	24, // 39: grpcproto.Vpn.StopHealthCheck:output_type -> grpcproto.Empty
	21, // 40: grpcproto.Vpn.CheckServerAlive:output_type -> grpcproto.CheckServerAliveResponce
	9,  // 41: grpcproto.Vpn.MeasureTunnelProbeAverageLatencyMillis:output_type -> grpcproto.MeasureTunnelProbeResponse
	24, // 42: grpcproto.Vpn.StartCloakClient:output_type -> grpcproto.Empty
	24, // 43: grpcproto.Vpn.StopCloakClient:output_type -> grpcproto.Empty
	24, // 44: grpcproto.Vpn.InitLogger:output_type -> grpcproto.Empty
	24, // 45: grpcproto.Vpn.InitTelemetry:output_type -> grpcproto.Empty
	24, // 46: grpcproto.Vpn.StopTelemetry:output_type -> grpcproto.Empty
	24, // 47: grpcproto.Vpn.SetupTelemetryAttributes:output_type -> grpcproto.Empty
	24, // 48: grpcproto.Vpn.SetGeoRoutingConf:output_type -> grpcproto.Empty
	24, // 49: grpcproto.Vpn.ClearGeoRoutingConf:output_type -> grpcproto.Empty
	24, // 50: grpcproto.Vpn.ClearDNSCache:output_type -> grpcproto.Empty
	23, // 51: grpcproto.Vpn.SetDNSCacheEntries:output_type -> grpcproto.SetDNSCacheEntriesResponse
	26, // [26:52] is the sub-list for method output_type
	0,  // [0:26] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_grpcproto_vpnserver_proto_init() }
func file_grpcproto_vpnserver_proto_init() {
	if File_grpcproto_vpnserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcproto_vpnserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOutlineLastErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartOutlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartOutlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXrayLastErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartXrayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartXrayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouldStartResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConnectionStateResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasureTunnelProbeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasureTunnelProbeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartCloakClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitLoggerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitTelemetryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetGeoRoutingConfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupTelemetryAttributesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrustTunnelLastErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartTrustTunnelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartTrustTunnelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckServerAliveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckServerAliveResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDNSCacheEntriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDNSCacheEntriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproto_vpnserver_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcproto_vpnserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcproto_vpnserver_proto_goTypes,
		DependencyIndexes: file_grpcproto_vpnserver_proto_depIdxs,
		MessageInfos:      file_grpcproto_vpnserver_proto_msgTypes,
	}.Build()
	File_grpcproto_vpnserver_proto = out.File
	file_grpcproto_vpnserver_proto_rawDesc = nil
	file_grpcproto_vpnserver_proto_goTypes = nil
	file_grpcproto_vpnserver_proto_depIdxs = nil
}
