// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.1
// source: grpcproto/vpnserver.proto

package grpcproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Vpn_InitLogger_FullMethodName     = "/grpcproto.Vpn/InitLogger"
	Vpn_ValidateConfig_FullMethodName = "/grpcproto.Vpn/ValidateConfig"
	Vpn_Configure_FullMethodName      = "/grpcproto.Vpn/Configure"
	Vpn_Start_FullMethodName          = "/grpcproto.Vpn/Start"
	Vpn_Stop_FullMethodName           = "/grpcproto.Vpn/Stop"
	Vpn_Snapshot_FullMethodName       = "/grpcproto.Vpn/Snapshot"
	Vpn_Watch_FullMethodName          = "/grpcproto.Vpn/Watch"
	Vpn_Reset_FullMethodName          = "/grpcproto.Vpn/Reset"
)

// VpnClient is the client API for Vpn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VpnClient interface {
	// Local diagnostics only. Remote telemetry is not a product feature.
	InitLogger(ctx context.Context, in *InitLoggerRequest, opts ...grpc.CallOption) (*Empty, error)
	// One process-owned session. Snapshot attaches clients after restart.
	ValidateConfig(ctx context.Context, in *SessionValidateConfigRequest, opts ...grpc.CallOption) (*SessionValidateConfigResponse, error)
	Configure(ctx context.Context, in *SessionConfigureRequest, opts ...grpc.CallOption) (*SessionConfigureResponse, error)
	Start(ctx context.Context, in *SessionStartRequest, opts ...grpc.CallOption) (*SessionStartResponse, error)
	Stop(ctx context.Context, in *SessionStopRequest, opts ...grpc.CallOption) (*SessionStopResponse, error)
	Snapshot(ctx context.Context, in *SessionSnapshotRequest, opts ...grpc.CallOption) (*SessionSnapshotResponse, error)
	Watch(ctx context.Context, in *SessionSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SessionSnapshot], error)
	Reset(ctx context.Context, in *SessionResetRequest, opts ...grpc.CallOption) (*SessionResetResponse, error)
}

type vpnClient struct {
	cc grpc.ClientConnInterface
}

func NewVpnClient(cc grpc.ClientConnInterface) VpnClient {
	return &vpnClient{cc}
}

func (c *vpnClient) InitLogger(ctx context.Context, in *InitLoggerRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Vpn_InitLogger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) ValidateConfig(ctx context.Context, in *SessionValidateConfigRequest, opts ...grpc.CallOption) (*SessionValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionValidateConfigResponse)
	err := c.cc.Invoke(ctx, Vpn_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) Configure(ctx context.Context, in *SessionConfigureRequest, opts ...grpc.CallOption) (*SessionConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionConfigureResponse)
	err := c.cc.Invoke(ctx, Vpn_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) Start(ctx context.Context, in *SessionStartRequest, opts ...grpc.CallOption) (*SessionStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionStartResponse)
	err := c.cc.Invoke(ctx, Vpn_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) Stop(ctx context.Context, in *SessionStopRequest, opts ...grpc.CallOption) (*SessionStopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionStopResponse)
	err := c.cc.Invoke(ctx, Vpn_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) Snapshot(ctx context.Context, in *SessionSnapshotRequest, opts ...grpc.CallOption) (*SessionSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionSnapshotResponse)
	err := c.cc.Invoke(ctx, Vpn_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnClient) Watch(ctx context.Context, in *SessionSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SessionSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Vpn_ServiceDesc.Streams[0], Vpn_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionSnapshotRequest, SessionSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vpn_WatchClient = grpc.ServerStreamingClient[SessionSnapshot]

func (c *vpnClient) Reset(ctx context.Context, in *SessionResetRequest, opts ...grpc.CallOption) (*SessionResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResetResponse)
	err := c.cc.Invoke(ctx, Vpn_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VpnServer is the server API for Vpn service.
// All implementations must embed UnimplementedVpnServer
// for forward compatibility.
type VpnServer interface {
	// Local diagnostics only. Remote telemetry is not a product feature.
	InitLogger(context.Context, *InitLoggerRequest) (*Empty, error)
	// One process-owned session. Snapshot attaches clients after restart.
	ValidateConfig(context.Context, *SessionValidateConfigRequest) (*SessionValidateConfigResponse, error)
	Configure(context.Context, *SessionConfigureRequest) (*SessionConfigureResponse, error)
	Start(context.Context, *SessionStartRequest) (*SessionStartResponse, error)
	Stop(context.Context, *SessionStopRequest) (*SessionStopResponse, error)
	Snapshot(context.Context, *SessionSnapshotRequest) (*SessionSnapshotResponse, error)
	Watch(*SessionSnapshotRequest, grpc.ServerStreamingServer[SessionSnapshot]) error
	Reset(context.Context, *SessionResetRequest) (*SessionResetResponse, error)
	mustEmbedUnimplementedVpnServer()
}

// UnimplementedVpnServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVpnServer struct{}

func (UnimplementedVpnServer) InitLogger(context.Context, *InitLoggerRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method InitLogger not implemented")
}
func (UnimplementedVpnServer) ValidateConfig(context.Context, *SessionValidateConfigRequest) (*SessionValidateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedVpnServer) Configure(context.Context, *SessionConfigureRequest) (*SessionConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedVpnServer) Start(context.Context, *SessionStartRequest) (*SessionStartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedVpnServer) Stop(context.Context, *SessionStopRequest) (*SessionStopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedVpnServer) Snapshot(context.Context, *SessionSnapshotRequest) (*SessionSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedVpnServer) Watch(*SessionSnapshotRequest, grpc.ServerStreamingServer[SessionSnapshot]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedVpnServer) Reset(context.Context, *SessionResetRequest) (*SessionResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedVpnServer) mustEmbedUnimplementedVpnServer() {}
func (UnimplementedVpnServer) testEmbeddedByValue()             {}

// UnsafeVpnServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VpnServer will
// result in compilation errors.
type UnsafeVpnServer interface {
	mustEmbedUnimplementedVpnServer()
}

func RegisterVpnServer(s grpc.ServiceRegistrar, srv VpnServer) {
	// If the following call panics, it indicates UnimplementedVpnServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Vpn_ServiceDesc, srv)
}

func _Vpn_InitLogger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitLoggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).InitLogger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_InitLogger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).InitLogger(ctx, req.(*InitLoggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).ValidateConfig(ctx, req.(*SessionValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).Configure(ctx, req.(*SessionConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).Start(ctx, req.(*SessionStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).Stop(ctx, req.(*SessionStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).Snapshot(ctx, req.(*SessionSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vpn_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SessionSnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VpnServer).Watch(m, &grpc.GenericServerStream[SessionSnapshotRequest, SessionSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Vpn_WatchServer = grpc.ServerStreamingServer[SessionSnapshot]

func _Vpn_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vpn_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnServer).Reset(ctx, req.(*SessionResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Vpn_ServiceDesc is the grpc.ServiceDesc for Vpn service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vpn_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcproto.Vpn",
	HandlerType: (*VpnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitLogger",
			Handler:    _Vpn_InitLogger_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _Vpn_ValidateConfig_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Vpn_Configure_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Vpn_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Vpn_Stop_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _Vpn_Snapshot_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _Vpn_Reset_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Vpn_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpcproto/vpnserver.proto",
}
