// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: grpcproto/vpnserver.proto

package grpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionProtocol int32

const (
	SessionProtocol_SESSION_PROTOCOL_UNSPECIFIED  SessionProtocol = 0
	SessionProtocol_SESSION_PROTOCOL_OUTLINE      SessionProtocol = 1
	SessionProtocol_SESSION_PROTOCOL_XRAY         SessionProtocol = 2
	SessionProtocol_SESSION_PROTOCOL_TRUST_TUNNEL SessionProtocol = 3
)

// Enum value maps for SessionProtocol.
var (
	SessionProtocol_name = map[int32]string{
		0: "SESSION_PROTOCOL_UNSPECIFIED",
		1: "SESSION_PROTOCOL_OUTLINE",
		2: "SESSION_PROTOCOL_XRAY",
		3: "SESSION_PROTOCOL_TRUST_TUNNEL",
	}
	SessionProtocol_value = map[string]int32{
		"SESSION_PROTOCOL_UNSPECIFIED":  0,
		"SESSION_PROTOCOL_OUTLINE":      1,
		"SESSION_PROTOCOL_XRAY":         2,
		"SESSION_PROTOCOL_TRUST_TUNNEL": 3,
	}
)

func (x SessionProtocol) Enum() *SessionProtocol {
	p := new(SessionProtocol)
	*p = x
	return p
}

func (x SessionProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcproto_vpnserver_proto_enumTypes[0].Descriptor()
}

func (SessionProtocol) Type() protoreflect.EnumType {
	return &file_grpcproto_vpnserver_proto_enumTypes[0]
}

func (x SessionProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionProtocol.Descriptor instead.
func (SessionProtocol) EnumDescriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{0}
}

type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED SessionState = 0
	SessionState_SESSION_STATE_IDLE        SessionState = 1
	SessionState_SESSION_STATE_CONFIGURED  SessionState = 2
	SessionState_SESSION_STATE_PROBING     SessionState = 3
	SessionState_SESSION_STATE_PREPARING   SessionState = 4
	SessionState_SESSION_STATE_CONNECTED   SessionState = 5
	SessionState_SESSION_STATE_STOPPING    SessionState = 6
	SessionState_SESSION_STATE_FAILED      SessionState = 7
	SessionState_SESSION_STATE_DESTROYED   SessionState = 8
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_IDLE",
		2: "SESSION_STATE_CONFIGURED",
		3: "SESSION_STATE_PROBING",
		4: "SESSION_STATE_PREPARING",
		5: "SESSION_STATE_CONNECTED",
		6: "SESSION_STATE_STOPPING",
		7: "SESSION_STATE_FAILED",
		8: "SESSION_STATE_DESTROYED",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED": 0,
		"SESSION_STATE_IDLE":        1,
		"SESSION_STATE_CONFIGURED":  2,
		"SESSION_STATE_PROBING":     3,
		"SESSION_STATE_PREPARING":   4,
		"SESSION_STATE_CONNECTED":   5,
		"SESSION_STATE_STOPPING":    6,
		"SESSION_STATE_FAILED":      7,
		"SESSION_STATE_DESTROYED":   8,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcproto_vpnserver_proto_enumTypes[1].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_grpcproto_vpnserver_proto_enumTypes[1]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{1}
}

type SessionFailureCode int32

const (
	SessionFailureCode_SESSION_FAILURE_CODE_UNSPECIFIED      SessionFailureCode = 0
	SessionFailureCode_SESSION_FAILURE_CODE_INVALID_ARGUMENT SessionFailureCode = 1
	SessionFailureCode_SESSION_FAILURE_CODE_NOT_FOUND        SessionFailureCode = 2
	SessionFailureCode_SESSION_FAILURE_CODE_CONFLICT         SessionFailureCode = 3
	SessionFailureCode_SESSION_FAILURE_CODE_NOT_CONFIGURED   SessionFailureCode = 4
	SessionFailureCode_SESSION_FAILURE_CODE_STALE_GENERATION SessionFailureCode = 5
	SessionFailureCode_SESSION_FAILURE_CODE_UNSUPPORTED      SessionFailureCode = 6
	SessionFailureCode_SESSION_FAILURE_CODE_MALFORMED_CONFIG SessionFailureCode = 7
	SessionFailureCode_SESSION_FAILURE_CODE_PROBE_FAILED     SessionFailureCode = 8
	SessionFailureCode_SESSION_FAILURE_CODE_PLATFORM_FAILED  SessionFailureCode = 9
	SessionFailureCode_SESSION_FAILURE_CODE_RUNTIME_FAILED   SessionFailureCode = 10
	SessionFailureCode_SESSION_FAILURE_CODE_CANCELED         SessionFailureCode = 11
	SessionFailureCode_SESSION_FAILURE_CODE_INTERNAL         SessionFailureCode = 12
	SessionFailureCode_SESSION_FAILURE_CODE_CLEANUP_FAILED   SessionFailureCode = 13
)

// Enum value maps for SessionFailureCode.
var (
	SessionFailureCode_name = map[int32]string{
		0:  "SESSION_FAILURE_CODE_UNSPECIFIED",
		1:  "SESSION_FAILURE_CODE_INVALID_ARGUMENT",
		2:  "SESSION_FAILURE_CODE_NOT_FOUND",
		3:  "SESSION_FAILURE_CODE_CONFLICT",
		4:  "SESSION_FAILURE_CODE_NOT_CONFIGURED",
		5:  "SESSION_FAILURE_CODE_STALE_GENERATION",
		6:  "SESSION_FAILURE_CODE_UNSUPPORTED",
		7:  "SESSION_FAILURE_CODE_MALFORMED_CONFIG",
		8:  "SESSION_FAILURE_CODE_PROBE_FAILED",
		9:  "SESSION_FAILURE_CODE_PLATFORM_FAILED",
		10: "SESSION_FAILURE_CODE_RUNTIME_FAILED",
		11: "SESSION_FAILURE_CODE_CANCELED",
		12: "SESSION_FAILURE_CODE_INTERNAL",
		13: "SESSION_FAILURE_CODE_CLEANUP_FAILED",
	}
	SessionFailureCode_value = map[string]int32{
		"SESSION_FAILURE_CODE_UNSPECIFIED":      0,
		"SESSION_FAILURE_CODE_INVALID_ARGUMENT": 1,
		"SESSION_FAILURE_CODE_NOT_FOUND":        2,
		"SESSION_FAILURE_CODE_CONFLICT":         3,
		"SESSION_FAILURE_CODE_NOT_CONFIGURED":   4,
		"SESSION_FAILURE_CODE_STALE_GENERATION": 5,
		"SESSION_FAILURE_CODE_UNSUPPORTED":      6,
		"SESSION_FAILURE_CODE_MALFORMED_CONFIG": 7,
		"SESSION_FAILURE_CODE_PROBE_FAILED":     8,
		"SESSION_FAILURE_CODE_PLATFORM_FAILED":  9,
		"SESSION_FAILURE_CODE_RUNTIME_FAILED":   10,
		"SESSION_FAILURE_CODE_CANCELED":         11,
		"SESSION_FAILURE_CODE_INTERNAL":         12,
		"SESSION_FAILURE_CODE_CLEANUP_FAILED":   13,
	}
)

func (x SessionFailureCode) Enum() *SessionFailureCode {
	p := new(SessionFailureCode)
	*p = x
	return p
}

func (x SessionFailureCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionFailureCode) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcproto_vpnserver_proto_enumTypes[2].Descriptor()
}

func (SessionFailureCode) Type() protoreflect.EnumType {
	return &file_grpcproto_vpnserver_proto_enumTypes[2]
}

func (x SessionFailureCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionFailureCode.Descriptor instead.
func (SessionFailureCode) EnumDescriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{2}
}

type SessionSourceKind int32

const (
	SessionSourceKind_SESSION_SOURCE_KIND_UNSPECIFIED SessionSourceKind = 0
	SessionSourceKind_SESSION_SOURCE_KIND_INLINE      SessionSourceKind = 1
	SessionSourceKind_SESSION_SOURCE_KIND_URL         SessionSourceKind = 2
)

// Enum value maps for SessionSourceKind.
var (
	SessionSourceKind_name = map[int32]string{
		0: "SESSION_SOURCE_KIND_UNSPECIFIED",
		1: "SESSION_SOURCE_KIND_INLINE",
		2: "SESSION_SOURCE_KIND_URL",
	}
	SessionSourceKind_value = map[string]int32{
		"SESSION_SOURCE_KIND_UNSPECIFIED": 0,
		"SESSION_SOURCE_KIND_INLINE":      1,
		"SESSION_SOURCE_KIND_URL":         2,
	}
)

func (x SessionSourceKind) Enum() *SessionSourceKind {
	p := new(SessionSourceKind)
	*p = x
	return p
}

func (x SessionSourceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionSourceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcproto_vpnserver_proto_enumTypes[3].Descriptor()
}

func (SessionSourceKind) Type() protoreflect.EnumType {
	return &file_grpcproto_vpnserver_proto_enumTypes[3]
}

func (x SessionSourceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionSourceKind.Descriptor instead.
func (SessionSourceKind) EnumDescriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{3}
}

type SessionStartMode int32

const (
	SessionStartMode_SESSION_START_MODE_UNSPECIFIED   SessionStartMode = 0
	SessionStartMode_SESSION_START_MODE_AUTO_SELECT   SessionStartMode = 1
	SessionStartMode_SESSION_START_MODE_PROFILE_INDEX SessionStartMode = 2
)

// Enum value maps for SessionStartMode.
var (
	SessionStartMode_name = map[int32]string{
		0: "SESSION_START_MODE_UNSPECIFIED",
		1: "SESSION_START_MODE_AUTO_SELECT",
		2: "SESSION_START_MODE_PROFILE_INDEX",
	}
	SessionStartMode_value = map[string]int32{
		"SESSION_START_MODE_UNSPECIFIED":   0,
		"SESSION_START_MODE_AUTO_SELECT":   1,
		"SESSION_START_MODE_PROFILE_INDEX": 2,
	}
)

func (x SessionStartMode) Enum() *SessionStartMode {
	p := new(SessionStartMode)
	*p = x
	return p
}

func (x SessionStartMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStartMode) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcproto_vpnserver_proto_enumTypes[4].Descriptor()
}

func (SessionStartMode) Type() protoreflect.EnumType {
	return &file_grpcproto_vpnserver_proto_enumTypes[4]
}

func (x SessionStartMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStartMode.Descriptor instead.
func (SessionStartMode) EnumDescriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{4}
}

type InitLoggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitLoggerRequest) Reset() {
	*x = InitLoggerRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitLoggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitLoggerRequest) ProtoMessage() {}

func (x *InitLoggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitLoggerRequest.ProtoReflect.Descriptor instead.
func (*InitLoggerRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{0}
}

func (x *InitLoggerRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{1}
}

// A failure is safe for display across the process boundary. Its message must
// never include configuration text, a connection URL, or credentials.
type SessionFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          SessionFailureCode     `protobuf:"varint,1,opt,name=code,proto3,enum=grpcproto.SessionFailureCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionFailure) Reset() {
	*x = SessionFailure{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionFailure) ProtoMessage() {}

func (x *SessionFailure) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionFailure.ProtoReflect.Descriptor instead.
func (*SessionFailure) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{2}
}

func (x *SessionFailure) GetCode() SessionFailureCode {
	if x != nil {
		return x.Code
	}
	return SessionFailureCode_SESSION_FAILURE_CODE_UNSPECIFIED
}

func (x *SessionFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// A profile intentionally omits server, address, and configuration fields.
type SessionProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Protocol      SessionProtocol        `protobuf:"varint,2,opt,name=protocol,proto3,enum=grpcproto.SessionProtocol" json:"protocol,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionProfile) Reset() {
	*x = SessionProfile{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionProfile) ProtoMessage() {}

func (x *SessionProfile) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionProfile.ProtoReflect.Descriptor instead.
func (*SessionProfile) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{3}
}

func (x *SessionProfile) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SessionProfile) GetProtocol() SessionProtocol {
	if x != nil {
		return x.Protocol
	}
	return SessionProtocol_SESSION_PROTOCOL_UNSPECIFIED
}

func (x *SessionProfile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SessionWarning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionWarning) Reset() {
	*x = SessionWarning{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionWarning) ProtoMessage() {}

func (x *SessionWarning) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionWarning.ProtoReflect.Descriptor instead.
func (*SessionWarning) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{4}
}

func (x *SessionWarning) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SessionWarning) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SessionFeature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionFeature) Reset() {
	*x = SessionFeature{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionFeature) ProtoMessage() {}

func (x *SessionFeature) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionFeature.ProtoReflect.Descriptor instead.
func (*SessionFeature) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{5}
}

func (x *SessionFeature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SessionFeature) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// An event is append-only and ordered by sequence within one session.
type SessionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	State         SessionState           `protobuf:"varint,4,opt,name=state,proto3,enum=grpcproto.SessionState" json:"state,omitempty"`
	Profile       *SessionProfile        `protobuf:"bytes,5,opt,name=profile,proto3" json:"profile,omitempty"`
	Failure       *SessionFailure        `protobuf:"bytes,6,opt,name=failure,proto3" json:"failure,omitempty"`
	Warning       *SessionWarning        `protobuf:"bytes,7,opt,name=warning,proto3" json:"warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{6}
}

func (x *SessionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEvent) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SessionEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SessionEvent) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *SessionEvent) GetProfile() *SessionProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *SessionEvent) GetFailure() *SessionFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *SessionEvent) GetWarning() *SessionWarning {
	if x != nil {
		return x.Warning
	}
	return nil
}

type SessionSnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Generation      uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	State           SessionState           `protobuf:"varint,3,opt,name=state,proto3,enum=grpcproto.SessionState" json:"state,omitempty"`
	Configured      bool                   `protobuf:"varint,4,opt,name=configured,proto3" json:"configured,omitempty"`
	ActiveProfile   *SessionProfile        `protobuf:"bytes,5,opt,name=active_profile,json=activeProfile,proto3" json:"active_profile,omitempty"`
	LastFailure     *SessionFailure        `protobuf:"bytes,6,opt,name=last_failure,json=lastFailure,proto3" json:"last_failure,omitempty"`
	CleanupComplete bool                   `protobuf:"varint,7,opt,name=cleanup_complete,json=cleanupComplete,proto3" json:"cleanup_complete,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionSnapshot) Reset() {
	*x = SessionSnapshot{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSnapshot) ProtoMessage() {}

func (x *SessionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSnapshot.ProtoReflect.Descriptor instead.
func (*SessionSnapshot) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{7}
}

func (x *SessionSnapshot) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSnapshot) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SessionSnapshot) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *SessionSnapshot) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *SessionSnapshot) GetActiveProfile() *SessionProfile {
	if x != nil {
		return x.ActiveProfile
	}
	return nil
}

func (x *SessionSnapshot) GetLastFailure() *SessionFailure {
	if x != nil {
		return x.LastFailure
	}
	return nil
}

func (x *SessionSnapshot) GetCleanupComplete() bool {
	if x != nil {
		return x.CleanupComplete
	}
	return false
}

type SessionGetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionGetCapabilitiesRequest) Reset() {
	*x = SessionGetCapabilitiesRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionGetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionGetCapabilitiesRequest) ProtoMessage() {}

func (x *SessionGetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionGetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*SessionGetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{8}
}

type SessionGetCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Protocols     []SessionProtocol      `protobuf:"varint,2,rep,packed,name=protocols,proto3,enum=grpcproto.SessionProtocol" json:"protocols,omitempty"`
	Features      []*SessionFeature      `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionGetCapabilitiesResponse) Reset() {
	*x = SessionGetCapabilitiesResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionGetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionGetCapabilitiesResponse) ProtoMessage() {}

func (x *SessionGetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionGetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*SessionGetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{9}
}

func (x *SessionGetCapabilitiesResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SessionGetCapabilitiesResponse) GetProtocols() []SessionProtocol {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *SessionGetCapabilitiesResponse) GetFeatures() []*SessionFeature {
	if x != nil {
		return x.Features
	}
	return nil
}

type SessionCreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCreateSessionRequest) Reset() {
	*x = SessionCreateSessionRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreateSessionRequest) ProtoMessage() {}

func (x *SessionCreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreateSessionRequest.ProtoReflect.Descriptor instead.
func (*SessionCreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{10}
}

type SessionCreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Failure       *SessionFailure        `protobuf:"bytes,100,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCreateSessionResponse) Reset() {
	*x = SessionCreateSessionResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreateSessionResponse) ProtoMessage() {}

func (x *SessionCreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreateSessionResponse.ProtoReflect.Descriptor instead.
func (*SessionCreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{11}
}

func (x *SessionCreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionCreateSessionResponse) GetFailure() *SessionFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type SessionRecoverActiveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Failure       *SessionFailure        `protobuf:"bytes,100,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRecoverActiveSessionResponse) Reset() {
	*x = SessionRecoverActiveSessionResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRecoverActiveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRecoverActiveSessionResponse) ProtoMessage() {}

func (x *SessionRecoverActiveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRecoverActiveSessionResponse.ProtoReflect.Descriptor instead.
func (*SessionRecoverActiveSessionResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{12}
}

func (x *SessionRecoverActiveSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionRecoverActiveSessionResponse) GetFailure() *SessionFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type SessionConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	RawConfig     []byte                 `protobuf:"bytes,3,opt,name=raw_config,json=rawConfig,proto3" json:"raw_config,omitempty"`
	SourceKind    SessionSourceKind      `protobuf:"varint,4,opt,name=source_kind,json=sourceKind,proto3,enum=grpcproto.SessionSourceKind" json:"source_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionConfigureRequest) Reset() {
	*x = SessionConfigureRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfigureRequest) ProtoMessage() {}

func (x *SessionConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfigureRequest.ProtoReflect.Descriptor instead.
func (*SessionConfigureRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{13}
}

func (x *SessionConfigureRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionConfigureRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SessionConfigureRequest) GetRawConfig() []byte {
	if x != nil {
		return x.RawConfig
	}
	return nil
}

func (x *SessionConfigureRequest) GetSourceKind() SessionSourceKind {
	if x != nil {
		return x.SourceKind
	}
	return SessionSourceKind_SESSION_SOURCE_KIND_UNSPECIFIED
}

type SessionConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Profiles      []*SessionProfile      `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty"`
	Warnings      []*SessionWarning      `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	SourceKind    SessionSourceKind      `protobuf:"varint,4,opt,name=source_kind,json=sourceKind,proto3,enum=grpcproto.SessionSourceKind" json:"source_kind,omitempty"`
	Failure       *SessionFailure        `protobuf:"bytes,100,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionConfigureResponse) Reset() {
	*x = SessionConfigureResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfigureResponse) ProtoMessage() {}

func (x *SessionConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfigureResponse.ProtoReflect.Descriptor instead.
func (*SessionConfigureResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{14}
}

func (x *SessionConfigureResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *SessionConfigureResponse) GetProfiles() []*SessionProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *SessionConfigureResponse) GetWarnings() []*SessionWarning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *SessionConfigureResponse) GetSourceKind() SessionSourceKind {
	if x != nil {
		return x.SourceKind
	}
	return SessionSourceKind_SESSION_SOURCE_KIND_UNSPECIFIED
}

func (x *SessionConfigureResponse) GetFailure() *SessionFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type SessionStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Mode          SessionStartMode       `protobuf:"varint,3,opt,name=mode,proto3,enum=grpcproto.SessionStartMode" json:"mode,omitempty"`
	ProfileIndex  int32                  `protobuf:"varint,4,opt,name=profile_index,json=profileIndex,proto3" json:"profile_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStartRequest) Reset() {
	*x = SessionStartRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartRequest) ProtoMessage() {}

func (x *SessionStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartRequest.ProtoReflect.Descriptor instead.
func (*SessionStartRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{15}
}

func (x *SessionStartRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStartRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SessionStartRequest) GetMode() SessionStartMode {
	if x != nil {
		return x.Mode
	}
	return SessionStartMode_SESSION_START_MODE_UNSPECIFIED
}

func (x *SessionStartRequest) GetProfileIndex() int32 {
	if x != nil {
		return x.ProfileIndex
	}
	return 0
}

type SessionStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Failure       *SessionFailure        `protobuf:"bytes,100,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStartResponse) Reset() {
	*x = SessionStartResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartResponse) ProtoMessage() {}

func (x *SessionStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartResponse.ProtoReflect.Descriptor instead.
func (*SessionStartResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{16}
}

func (x *SessionStartResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SessionStartResponse) GetFailure() *SessionFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type SessionStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStopRequest) Reset() {
	*x = SessionStopRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStopRequest) ProtoMessage() {}

func (x *SessionStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStopRequest.ProtoReflect.Descriptor instead.
func (*SessionStopRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{17}
}

func (x *SessionStopRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStopRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SessionStopRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type SessionStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Failure       *SessionFailure        `protobuf:"bytes,100,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStopResponse) Reset() {
	*x = SessionStopResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStopResponse) ProtoMessage() {}

func (x *SessionStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStopResponse.ProtoReflect.Descriptor instead.
func (*SessionStopResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{18}
}

func (x *SessionStopResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SessionStopResponse) GetFailure() *SessionFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type SessionSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSnapshotRequest) Reset() {
	*x = SessionSnapshotRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSnapshotRequest) ProtoMessage() {}

func (x *SessionSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSnapshotRequest.ProtoReflect.Descriptor instead.
func (*SessionSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{19}
}

func (x *SessionSnapshotRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *SessionSnapshot       `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Failure       *SessionFailure        `protobuf:"bytes,100,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSnapshotResponse) Reset() {
	*x = SessionSnapshotResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSnapshotResponse) ProtoMessage() {}

func (x *SessionSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSnapshotResponse.ProtoReflect.Descriptor instead.
func (*SessionSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{20}
}

func (x *SessionSnapshotResponse) GetSnapshot() *SessionSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *SessionSnapshotResponse) GetFailure() *SessionFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type SessionObserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AfterSequence uint64                 `protobuf:"varint,2,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionObserveRequest) Reset() {
	*x = SessionObserveRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionObserveRequest) ProtoMessage() {}

func (x *SessionObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionObserveRequest.ProtoReflect.Descriptor instead.
func (*SessionObserveRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{21}
}

func (x *SessionObserveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionObserveRequest) GetAfterSequence() uint64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

type SessionObserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*SessionEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextSequence  uint64                 `protobuf:"varint,2,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	Failure       *SessionFailure        `protobuf:"bytes,100,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionObserveResponse) Reset() {
	*x = SessionObserveResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionObserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionObserveResponse) ProtoMessage() {}

func (x *SessionObserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionObserveResponse.ProtoReflect.Descriptor instead.
func (*SessionObserveResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{22}
}

func (x *SessionObserveResponse) GetEvents() []*SessionEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SessionObserveResponse) GetNextSequence() uint64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

func (x *SessionObserveResponse) GetFailure() *SessionFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type SessionDestroySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionDestroySessionRequest) Reset() {
	*x = SessionDestroySessionRequest{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDestroySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDestroySessionRequest) ProtoMessage() {}

func (x *SessionDestroySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDestroySessionRequest.ProtoReflect.Descriptor instead.
func (*SessionDestroySessionRequest) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{23}
}

func (x *SessionDestroySessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionDestroySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destroyed     bool                   `protobuf:"varint,1,opt,name=destroyed,proto3" json:"destroyed,omitempty"`
	Failure       *SessionFailure        `protobuf:"bytes,100,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionDestroySessionResponse) Reset() {
	*x = SessionDestroySessionResponse{}
	mi := &file_grpcproto_vpnserver_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDestroySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDestroySessionResponse) ProtoMessage() {}

func (x *SessionDestroySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproto_vpnserver_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDestroySessionResponse.ProtoReflect.Descriptor instead.
func (*SessionDestroySessionResponse) Descriptor() ([]byte, []int) {
	return file_grpcproto_vpnserver_proto_rawDescGZIP(), []int{24}
}

func (x *SessionDestroySessionResponse) GetDestroyed() bool {
	if x != nil {
		return x.Destroyed
	}
	return false
}

func (x *SessionDestroySessionResponse) GetFailure() *SessionFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

var File_grpcproto_vpnserver_proto protoreflect.FileDescriptor

const file_grpcproto_vpnserver_proto_rawDesc = "" +
	"\n" +
	"\x19grpcproto/vpnserver.proto\x12\tgrpcproto\"'\n" +
	"\x11InitLoggerRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\a\n" +
	"\x05Empty\"]\n" +
	"\x0eSessionFailure\x121\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1d.grpcproto.SessionFailureCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x80\x01\n" +
	"\x0eSessionProfile\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x126\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x1a.grpcproto.SessionProtocolR\bprotocol\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\">\n" +
	"\x0eSessionWarning\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\x0eSessionFeature\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\xb7\x02\n" +
	"\fSessionEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12-\n" +
	"\x05state\x18\x04 \x01(\x0e2\x17.grpcproto.SessionStateR\x05state\x123\n" +
	"\aprofile\x18\x05 \x01(\v2\x19.grpcproto.SessionProfileR\aprofile\x123\n" +
	"\afailure\x18\x06 \x01(\v2\x19.grpcproto.SessionFailureR\afailure\x123\n" +
	"\awarning\x18\a \x01(\v2\x19.grpcproto.SessionWarningR\awarning\"\xca\x02\n" +
	"\x0fSessionSnapshot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12-\n" +
	"\x05state\x18\x03 \x01(\x0e2\x17.grpcproto.SessionStateR\x05state\x12\x1e\n" +
	"\n" +
	"configured\x18\x04 \x01(\bR\n" +
	"configured\x12@\n" +
	"\x0eactive_profile\x18\x05 \x01(\v2\x19.grpcproto.SessionProfileR\ractiveProfile\x12<\n" +
	"\flast_failure\x18\x06 \x01(\v2\x19.grpcproto.SessionFailureR\vlastFailure\x12)\n" +
	"\x10cleanup_complete\x18\a \x01(\bR\x0fcleanupComplete\"\x1f\n" +
	"\x1dSessionGetCapabilitiesRequest\"\xb1\x01\n" +
	"\x1eSessionGetCapabilitiesResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x128\n" +
	"\tprotocols\x18\x02 \x03(\x0e2\x1a.grpcproto.SessionProtocolR\tprotocols\x125\n" +
	"\bfeatures\x18\x03 \x03(\v2\x19.grpcproto.SessionFeatureR\bfeaturesJ\x04\b\x04\x10\x05\"\x1d\n" +
	"\x1bSessionCreateSessionRequest\"r\n" +
	"\x1cSessionCreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x123\n" +
	"\afailure\x18d \x01(\v2\x19.grpcproto.SessionFailureR\afailure\"y\n" +
	"#SessionRecoverActiveSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x123\n" +
	"\afailure\x18d \x01(\v2\x19.grpcproto.SessionFailureR\afailure\"\xb5\x01\n" +
	"\x17SessionConfigureRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x1d\n" +
	"\n" +
	"raw_config\x18\x03 \x01(\fR\trawConfig\x12=\n" +
	"\vsource_kind\x18\x04 \x01(\x0e2\x1c.grpcproto.SessionSourceKindR\n" +
	"sourceKind\"\x94\x02\n" +
	"\x18SessionConfigureResponse\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x125\n" +
	"\bprofiles\x18\x02 \x03(\v2\x19.grpcproto.SessionProfileR\bprofiles\x125\n" +
	"\bwarnings\x18\x03 \x03(\v2\x19.grpcproto.SessionWarningR\bwarnings\x12=\n" +
	"\vsource_kind\x18\x04 \x01(\x0e2\x1c.grpcproto.SessionSourceKindR\n" +
	"sourceKind\x123\n" +
	"\afailure\x18d \x01(\v2\x19.grpcproto.SessionFailureR\afailure\"\xa9\x01\n" +
	"\x13SessionStartRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12/\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x1b.grpcproto.SessionStartModeR\x04mode\x12#\n" +
	"\rprofile_index\x18\x04 \x01(\x05R\fprofileIndex\"k\n" +
	"\x14SessionStartResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x123\n" +
	"\afailure\x18d \x01(\v2\x19.grpcproto.SessionFailureR\afailure\"r\n" +
	"\x12SessionStopRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\"j\n" +
	"\x13SessionStopResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x123\n" +
	"\afailure\x18d \x01(\v2\x19.grpcproto.SessionFailureR\afailure\"7\n" +
	"\x16SessionSnapshotRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x86\x01\n" +
	"\x17SessionSnapshotResponse\x126\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1a.grpcproto.SessionSnapshotR\bsnapshot\x123\n" +
	"\afailure\x18d \x01(\v2\x19.grpcproto.SessionFailureR\afailure\"]\n" +
	"\x15SessionObserveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0eafter_sequence\x18\x02 \x01(\x04R\rafterSequence\"\xa3\x01\n" +
	"\x16SessionObserveResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.grpcproto.SessionEventR\x06events\x12#\n" +
	"\rnext_sequence\x18\x02 \x01(\x04R\fnextSequence\x123\n" +
	"\afailure\x18d \x01(\v2\x19.grpcproto.SessionFailureR\afailure\"=\n" +
	"\x1cSessionDestroySessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"r\n" +
	"\x1dSessionDestroySessionResponse\x12\x1c\n" +
	"\tdestroyed\x18\x01 \x01(\bR\tdestroyed\x123\n" +
	"\afailure\x18d \x01(\v2\x19.grpcproto.SessionFailureR\afailure*\x8f\x01\n" +
	"\x0fSessionProtocol\x12 \n" +
	"\x1cSESSION_PROTOCOL_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SESSION_PROTOCOL_OUTLINE\x10\x01\x12\x19\n" +
	"\x15SESSION_PROTOCOL_XRAY\x10\x02\x12!\n" +
	"\x1dSESSION_PROTOCOL_TRUST_TUNNEL\x10\x03*\x8b\x02\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SESSION_STATE_IDLE\x10\x01\x12\x1c\n" +
	"\x18SESSION_STATE_CONFIGURED\x10\x02\x12\x19\n" +
	"\x15SESSION_STATE_PROBING\x10\x03\x12\x1b\n" +
	"\x17SESSION_STATE_PREPARING\x10\x04\x12\x1b\n" +
	"\x17SESSION_STATE_CONNECTED\x10\x05\x12\x1a\n" +
	"\x16SESSION_STATE_STOPPING\x10\x06\x12\x18\n" +
	"\x14SESSION_STATE_FAILED\x10\a\x12\x1b\n" +
	"\x17SESSION_STATE_DESTROYED\x10\b*\xba\x04\n" +
	"\x12SessionFailureCode\x12$\n" +
	" SESSION_FAILURE_CODE_UNSPECIFIED\x10\x00\x12)\n" +
	"%SESSION_FAILURE_CODE_INVALID_ARGUMENT\x10\x01\x12\"\n" +
	"\x1eSESSION_FAILURE_CODE_NOT_FOUND\x10\x02\x12!\n" +
	"\x1dSESSION_FAILURE_CODE_CONFLICT\x10\x03\x12'\n" +
	"#SESSION_FAILURE_CODE_NOT_CONFIGURED\x10\x04\x12)\n" +
	"%SESSION_FAILURE_CODE_STALE_GENERATION\x10\x05\x12$\n" +
	" SESSION_FAILURE_CODE_UNSUPPORTED\x10\x06\x12)\n" +
	"%SESSION_FAILURE_CODE_MALFORMED_CONFIG\x10\a\x12%\n" +
	"!SESSION_FAILURE_CODE_PROBE_FAILED\x10\b\x12(\n" +
	"$SESSION_FAILURE_CODE_PLATFORM_FAILED\x10\t\x12'\n" +
	"#SESSION_FAILURE_CODE_RUNTIME_FAILED\x10\n" +
	"\x12!\n" +
	"\x1dSESSION_FAILURE_CODE_CANCELED\x10\v\x12!\n" +
	"\x1dSESSION_FAILURE_CODE_INTERNAL\x10\f\x12'\n" +
	"#SESSION_FAILURE_CODE_CLEANUP_FAILED\x10\r*u\n" +
	"\x11SessionSourceKind\x12#\n" +
	"\x1fSESSION_SOURCE_KIND_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSESSION_SOURCE_KIND_INLINE\x10\x01\x12\x1b\n" +
	"\x17SESSION_SOURCE_KIND_URL\x10\x02*\x80\x01\n" +
	"\x10SessionStartMode\x12\"\n" +
	"\x1eSESSION_START_MODE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSESSION_START_MODE_AUTO_SELECT\x10\x01\x12$\n" +
	" SESSION_START_MODE_PROFILE_INDEX\x10\x022\x9c\a\n" +
	"\x03Vpn\x12<\n" +
	"\n" +
	"InitLogger\x12\x1c.grpcproto.InitLoggerRequest\x1a\x10.grpcproto.Empty\x12f\n" +
	"\x0fGetCapabilities\x12(.grpcproto.SessionGetCapabilitiesRequest\x1a).grpcproto.SessionGetCapabilitiesResponse\x12`\n" +
	"\rCreateSession\x12&.grpcproto.SessionCreateSessionRequest\x1a'.grpcproto.SessionCreateSessionResponse\x12X\n" +
	"\x14RecoverActiveSession\x12\x10.grpcproto.Empty\x1a..grpcproto.SessionRecoverActiveSessionResponse\x12T\n" +
	"\tConfigure\x12\".grpcproto.SessionConfigureRequest\x1a#.grpcproto.SessionConfigureResponse\x12H\n" +
	"\x05Start\x12\x1e.grpcproto.SessionStartRequest\x1a\x1f.grpcproto.SessionStartResponse\x12E\n" +
	"\x04Stop\x12\x1d.grpcproto.SessionStopRequest\x1a\x1e.grpcproto.SessionStopResponse\x12Q\n" +
	"\bSnapshot\x12!.grpcproto.SessionSnapshotRequest\x1a\".grpcproto.SessionSnapshotResponse\x12N\n" +
	"\aObserve\x12 .grpcproto.SessionObserveRequest\x1a!.grpcproto.SessionObserveResponse\x12D\n" +
	"\x05Watch\x12 .grpcproto.SessionObserveRequest\x1a\x17.grpcproto.SessionEvent0\x01\x12c\n" +
	"\x0eDestroySession\x12'.grpcproto.SessionDestroySessionRequest\x1a(.grpcproto.SessionDestroySessionResponseB7\n" +
	"\x13com.dobby.grpcprotoB\tGrpcProtoP\x01Z\x13go_module/grpcprotob\x06proto3"

var (
	file_grpcproto_vpnserver_proto_rawDescOnce sync.Once
	file_grpcproto_vpnserver_proto_rawDescData []byte
)

func file_grpcproto_vpnserver_proto_rawDescGZIP() []byte {
	file_grpcproto_vpnserver_proto_rawDescOnce.Do(func() {
		file_grpcproto_vpnserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcproto_vpnserver_proto_rawDesc), len(file_grpcproto_vpnserver_proto_rawDesc)))
	})
	return file_grpcproto_vpnserver_proto_rawDescData
}

var file_grpcproto_vpnserver_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_grpcproto_vpnserver_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_grpcproto_vpnserver_proto_goTypes = []any{
	(SessionProtocol)(0),                        // 0: grpcproto.SessionProtocol
	(SessionState)(0),                           // 1: grpcproto.SessionState
	(SessionFailureCode)(0),                     // 2: grpcproto.SessionFailureCode
	(SessionSourceKind)(0),                      // 3: grpcproto.SessionSourceKind
	(SessionStartMode)(0),                       // 4: grpcproto.SessionStartMode
	(*InitLoggerRequest)(nil),                   // 5: grpcproto.InitLoggerRequest
	(*Empty)(nil),                               // 6: grpcproto.Empty
	(*SessionFailure)(nil),                      // 7: grpcproto.SessionFailure
	(*SessionProfile)(nil),                      // 8: grpcproto.SessionProfile
	(*SessionWarning)(nil),                      // 9: grpcproto.SessionWarning
	(*SessionFeature)(nil),                      // 10: grpcproto.SessionFeature
	(*SessionEvent)(nil),                        // 11: grpcproto.SessionEvent
	(*SessionSnapshot)(nil),                     // 12: grpcproto.SessionSnapshot
	(*SessionGetCapabilitiesRequest)(nil),       // 13: grpcproto.SessionGetCapabilitiesRequest
	(*SessionGetCapabilitiesResponse)(nil),      // 14: grpcproto.SessionGetCapabilitiesResponse
	(*SessionCreateSessionRequest)(nil),         // 15: grpcproto.SessionCreateSessionRequest
	(*SessionCreateSessionResponse)(nil),        // 16: grpcproto.SessionCreateSessionResponse
	(*SessionRecoverActiveSessionResponse)(nil), // 17: grpcproto.SessionRecoverActiveSessionResponse
	(*SessionConfigureRequest)(nil),             // 18: grpcproto.SessionConfigureRequest
	(*SessionConfigureResponse)(nil),            // 19: grpcproto.SessionConfigureResponse
	(*SessionStartRequest)(nil),                 // 20: grpcproto.SessionStartRequest
	(*SessionStartResponse)(nil),                // 21: grpcproto.SessionStartResponse
	(*SessionStopRequest)(nil),                  // 22: grpcproto.SessionStopRequest
	(*SessionStopResponse)(nil),                 // 23: grpcproto.SessionStopResponse
	(*SessionSnapshotRequest)(nil),              // 24: grpcproto.SessionSnapshotRequest
	(*SessionSnapshotResponse)(nil),             // 25: grpcproto.SessionSnapshotResponse
	(*SessionObserveRequest)(nil),               // 26: grpcproto.SessionObserveRequest
	(*SessionObserveResponse)(nil),              // 27: grpcproto.SessionObserveResponse
	(*SessionDestroySessionRequest)(nil),        // 28: grpcproto.SessionDestroySessionRequest
	(*SessionDestroySessionResponse)(nil),       // 29: grpcproto.SessionDestroySessionResponse
}
var file_grpcproto_vpnserver_proto_depIdxs = []int32{
	2,  // 0: grpcproto.SessionFailure.code:type_name -> grpcproto.SessionFailureCode
	0,  // 1: grpcproto.SessionProfile.protocol:type_name -> grpcproto.SessionProtocol
	1,  // 2: grpcproto.SessionEvent.state:type_name -> grpcproto.SessionState
	8,  // 3: grpcproto.SessionEvent.profile:type_name -> grpcproto.SessionProfile
	7,  // 4: grpcproto.SessionEvent.failure:type_name -> grpcproto.SessionFailure
	9,  // 5: grpcproto.SessionEvent.warning:type_name -> grpcproto.SessionWarning
	1,  // 6: grpcproto.SessionSnapshot.state:type_name -> grpcproto.SessionState
	8,  // 7: grpcproto.SessionSnapshot.active_profile:type_name -> grpcproto.SessionProfile
	7,  // 8: grpcproto.SessionSnapshot.last_failure:type_name -> grpcproto.SessionFailure
	0,  // 9: grpcproto.SessionGetCapabilitiesResponse.protocols:type_name -> grpcproto.SessionProtocol
	10, // 10: grpcproto.SessionGetCapabilitiesResponse.features:type_name -> grpcproto.SessionFeature
	7,  // 11: grpcproto.SessionCreateSessionResponse.failure:type_name -> grpcproto.SessionFailure
	7,  // 12: grpcproto.SessionRecoverActiveSessionResponse.failure:type_name -> grpcproto.SessionFailure
	3,  // 13: grpcproto.SessionConfigureRequest.source_kind:type_name -> grpcproto.SessionSourceKind
	8,  // 14: grpcproto.SessionConfigureResponse.profiles:type_name -> grpcproto.SessionProfile
	9,  // 15: grpcproto.SessionConfigureResponse.warnings:type_name -> grpcproto.SessionWarning
	3,  // 16: grpcproto.SessionConfigureResponse.source_kind:type_name -> grpcproto.SessionSourceKind
	7,  // 17: grpcproto.SessionConfigureResponse.failure:type_name -> grpcproto.SessionFailure
	4,  // 18: grpcproto.SessionStartRequest.mode:type_name -> grpcproto.SessionStartMode
	7,  // 19: grpcproto.SessionStartResponse.failure:type_name -> grpcproto.SessionFailure
	7,  // 20: grpcproto.SessionStopResponse.failure:type_name -> grpcproto.SessionFailure
	12, // 21: grpcproto.SessionSnapshotResponse.snapshot:type_name -> grpcproto.SessionSnapshot
	7,  // 22: grpcproto.SessionSnapshotResponse.failure:type_name -> grpcproto.SessionFailure
	11, // 23: grpcproto.SessionObserveResponse.events:type_name -> grpcproto.SessionEvent
	7,  // 24: grpcproto.SessionObserveResponse.failure:type_name -> grpcproto.SessionFailure
	7,  // 25: grpcproto.SessionDestroySessionResponse.failure:type_name -> grpcproto.SessionFailure
	5,  // 26: grpcproto.Vpn.InitLogger:input_type -> grpcproto.InitLoggerRequest
	13, // 27: grpcproto.Vpn.GetCapabilities:input_type -> grpcproto.SessionGetCapabilitiesRequest
	15, // 28: grpcproto.Vpn.CreateSession:input_type -> grpcproto.SessionCreateSessionRequest
	6,  // 29: grpcproto.Vpn.RecoverActiveSession:input_type -> grpcproto.Empty
	18, // 30: grpcproto.Vpn.Configure:input_type -> grpcproto.SessionConfigureRequest
	20, // 31: grpcproto.Vpn.Start:input_type -> grpcproto.SessionStartRequest
	22, // 32: grpcproto.Vpn.Stop:input_type -> grpcproto.SessionStopRequest
	24, // 33: grpcproto.Vpn.Snapshot:input_type -> grpcproto.SessionSnapshotRequest
	26, // 34: grpcproto.Vpn.Observe:input_type -> grpcproto.SessionObserveRequest
	26, // 35: grpcproto.Vpn.Watch:input_type -> grpcproto.SessionObserveRequest
	28, // 36: grpcproto.Vpn.DestroySession:input_type -> grpcproto.SessionDestroySessionRequest
	6,  // 37: grpcproto.Vpn.InitLogger:output_type -> grpcproto.Empty
	14, // 38: grpcproto.Vpn.GetCapabilities:output_type -> grpcproto.SessionGetCapabilitiesResponse
	16, // 39: grpcproto.Vpn.CreateSession:output_type -> grpcproto.SessionCreateSessionResponse
	17, // 40: grpcproto.Vpn.RecoverActiveSession:output_type -> grpcproto.SessionRecoverActiveSessionResponse
	19, // 41: grpcproto.Vpn.Configure:output_type -> grpcproto.SessionConfigureResponse
	21, // 42: grpcproto.Vpn.Start:output_type -> grpcproto.SessionStartResponse
	23, // 43: grpcproto.Vpn.Stop:output_type -> grpcproto.SessionStopResponse
	25, // 44: grpcproto.Vpn.Snapshot:output_type -> grpcproto.SessionSnapshotResponse
	27, // 45: grpcproto.Vpn.Observe:output_type -> grpcproto.SessionObserveResponse
	11, // 46: grpcproto.Vpn.Watch:output_type -> grpcproto.SessionEvent
	29, // 47: grpcproto.Vpn.DestroySession:output_type -> grpcproto.SessionDestroySessionResponse
	37, // [37:48] is the sub-list for method output_type
	26, // [26:37] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_grpcproto_vpnserver_proto_init() }
func file_grpcproto_vpnserver_proto_init() {
	if File_grpcproto_vpnserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcproto_vpnserver_proto_rawDesc), len(file_grpcproto_vpnserver_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcproto_vpnserver_proto_goTypes,
		DependencyIndexes: file_grpcproto_vpnserver_proto_depIdxs,
		EnumInfos:         file_grpcproto_vpnserver_proto_enumTypes,
		MessageInfos:      file_grpcproto_vpnserver_proto_msgTypes,
	}.Build()
	File_grpcproto_vpnserver_proto = out.File
	file_grpcproto_vpnserver_proto_goTypes = nil
	file_grpcproto_vpnserver_proto_depIdxs = nil
}
