package com.dobby.feature.main.domain.config

import com.dobby.feature.logging.Logger
import com.dobby.feature.main.domain.DobbyConfigsRepositoryTrustTunnel
import com.dobby.feature.main.domain.TrustTunnelClientConfig
import com.dobby.feature.main.domain.clearTrustTunnelConfig
import kotlinx.serialization.encodeToString
import net.peanuuutz.tomlkt.Toml

internal class TrustTunnelTomlApplier(
    private val trustTunnelRepo: DobbyConfigsRepositoryTrustTunnel,
    private val logger: Logger,
) {
    // We create a TOML instance to encode the config back to a string
    private val toml = Toml {
        ignoreUnknownKeys = true
    }

    fun apply(config: TrustTunnelClientConfig): Boolean {
        logger.log("Applying generic [TrustTunnel] configuration")

        // TrustTunnel strictly requires an endpoint to connect to
        if (config.endpoint == null) {
            logger.log("Invalid [TrustTunnel]: Config is empty (no endpoint).")
            trustTunnelRepo.clearTrustTunnelConfig()
            return false
        }

        try {
            // Encode the data class back into a raw TOML string
            val rawToml = toml.encodeToString(config)

            // TOML 1.0 strictly prohibits 'null' values.
            // We must filter out any 'key = null' lines generated by tomlkt.
            val cleanTomlString = rawToml.lines()
                .filterNot { it.trim().endsWith("= null") }
                .joinToString("\n")

            logger.log("Successfully parsed TrustTunnel config")
            trustTunnelRepo.setTrustTunnelConfig(cleanTomlString)
            trustTunnelRepo.setIsTrustTunnelEnabled(true)
            return true

        } catch (e: Exception) {
            logger.log("Failed to encode TrustTunnel TOML: ${e.message}")
            trustTunnelRepo.clearTrustTunnelConfig()
            return false
        }
    }
}
