# golangci-lint v2 configuration
# Docs: https://golangci-lint.run/docs/configuration/file/

version: "2"

run:
  timeout: 5m

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
  sort-order:
    - linter
    - file

linters:
  enable:
    - bodyclose
    - nilerr
    - gosec
    - revive
    - gocritic
    - misspell
    - unconvert
    - prealloc
    - goconst
    - gocyclo
    - nestif
    - unparam
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocyclo:
      min-complexity: 20
    nestif:
      min-complexity: 5
    goconst:
      min-len: 3
      min-occurrences: 3
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          disabled: true
        - name: increment-decrement
        - name: var-naming
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
    gosec:
      excludes:
        - G104
        - G302
        - G304
        - G306
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam
        - rangeValCopy
  exclusions:
    paths:
      - ios_exports
      - kotlin_exports
      - desktop_exports
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - goconst
          - gosec
          - gocritic

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
