
included:
  - iosApp
  - CommonDI
  - tunnel

excluded:
  - app.framework

disabled_rules:
  - trailing_comma
  - opening_brace

opt_in_rules:
  - closure_body_length
  - closure_end_indentation
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_in_static_references
  - private_action
  - private_outlet
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces

line_length:
  warning: 140
  error: 250
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 100
  error: 150

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 3
  max_length: 50
  excluded:
    - iOSApp

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - ip

nesting:
  type_level: 2
  function_level: 3

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "xcode"
