// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.33.0
// source: vpnserver.proto

package vpnserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartAwgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tunnel string `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	Config string `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *StartAwgRequest) Reset() {
	*x = StartAwgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vpnserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartAwgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAwgRequest) ProtoMessage() {}

func (x *StartAwgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpnserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAwgRequest.ProtoReflect.Descriptor instead.
func (*StartAwgRequest) Descriptor() ([]byte, []int) {
	return file_vpnserver_proto_rawDescGZIP(), []int{0}
}

func (x *StartAwgRequest) GetTunnel() string {
	if x != nil {
		return x.Tunnel
	}
	return ""
}

func (x *StartAwgRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type StartOutlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *StartOutlineRequest) Reset() {
	*x = StartOutlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vpnserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartOutlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOutlineRequest) ProtoMessage() {}

func (x *StartOutlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpnserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOutlineRequest.ProtoReflect.Descriptor instead.
func (*StartOutlineRequest) Descriptor() ([]byte, []int) {
	return file_vpnserver_proto_rawDescGZIP(), []int{1}
}

func (x *StartOutlineRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type StartHealthCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Period      int32 `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
	SendMetrics bool  `protobuf:"varint,2,opt,name=sendMetrics,proto3" json:"sendMetrics,omitempty"`
}

func (x *StartHealthCheckRequest) Reset() {
	*x = StartHealthCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vpnserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartHealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartHealthCheckRequest) ProtoMessage() {}

func (x *StartHealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpnserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartHealthCheckRequest.ProtoReflect.Descriptor instead.
func (*StartHealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_vpnserver_proto_rawDescGZIP(), []int{2}
}

func (x *StartHealthCheckRequest) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *StartHealthCheckRequest) GetSendMetrics() bool {
	if x != nil {
		return x.SendMetrics
	}
	return false
}

type StatusResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StatusResponce) Reset() {
	*x = StatusResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vpnserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponce) ProtoMessage() {}

func (x *StatusResponce) ProtoReflect() protoreflect.Message {
	mi := &file_vpnserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponce.ProtoReflect.Descriptor instead.
func (*StatusResponce) Descriptor() ([]byte, []int) {
	return file_vpnserver_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponce) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TcpPingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *TcpPingRequest) Reset() {
	*x = TcpPingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vpnserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcpPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpPingRequest) ProtoMessage() {}

func (x *TcpPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpnserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpPingRequest.ProtoReflect.Descriptor instead.
func (*TcpPingRequest) Descriptor() ([]byte, []int) {
	return file_vpnserver_proto_rawDescGZIP(), []int{4}
}

func (x *TcpPingRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TcpPingResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *TcpPingResponce) Reset() {
	*x = TcpPingResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vpnserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcpPingResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpPingResponce) ProtoMessage() {}

func (x *TcpPingResponce) ProtoReflect() protoreflect.Message {
	mi := &file_vpnserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpPingResponce.ProtoReflect.Descriptor instead.
func (*TcpPingResponce) Descriptor() ([]byte, []int) {
	return file_vpnserver_proto_rawDescGZIP(), []int{5}
}

func (x *TcpPingResponce) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TcpPingResponce) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UrlTestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Standard int32  `protobuf:"varint,2,opt,name=standard,proto3" json:"standard,omitempty"`
}

func (x *UrlTestRequest) Reset() {
	*x = UrlTestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vpnserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UrlTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlTestRequest) ProtoMessage() {}

func (x *UrlTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpnserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlTestRequest.ProtoReflect.Descriptor instead.
func (*UrlTestRequest) Descriptor() ([]byte, []int) {
	return file_vpnserver_proto_rawDescGZIP(), []int{6}
}

func (x *UrlTestRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UrlTestRequest) GetStandard() int32 {
	if x != nil {
		return x.Standard
	}
	return 0
}

type UrlTestResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UrlTestResponce) Reset() {
	*x = UrlTestResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vpnserver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UrlTestResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlTestResponce) ProtoMessage() {}

func (x *UrlTestResponce) ProtoReflect() protoreflect.Message {
	mi := &file_vpnserver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlTestResponce.ProtoReflect.Descriptor instead.
func (*UrlTestResponce) Descriptor() ([]byte, []int) {
	return file_vpnserver_proto_rawDescGZIP(), []int{7}
}

func (x *UrlTestResponce) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *UrlTestResponce) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CouldStartResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CouldStartResponce) Reset() {
	*x = CouldStartResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vpnserver_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouldStartResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouldStartResponce) ProtoMessage() {}

func (x *CouldStartResponce) ProtoReflect() protoreflect.Message {
	mi := &file_vpnserver_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouldStartResponce.ProtoReflect.Descriptor instead.
func (*CouldStartResponce) Descriptor() ([]byte, []int) {
	return file_vpnserver_proto_rawDescGZIP(), []int{8}
}

func (x *CouldStartResponce) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type StartCloakClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalHost string `protobuf:"bytes,1,opt,name=localHost,proto3" json:"localHost,omitempty"`
	LocalPort string `protobuf:"bytes,2,opt,name=localPort,proto3" json:"localPort,omitempty"`
	Config    string `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Udp       bool   `protobuf:"varint,4,opt,name=udp,proto3" json:"udp,omitempty"`
}

func (x *StartCloakClientRequest) Reset() {
	*x = StartCloakClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vpnserver_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCloakClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCloakClientRequest) ProtoMessage() {}

func (x *StartCloakClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpnserver_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCloakClientRequest.ProtoReflect.Descriptor instead.
func (*StartCloakClientRequest) Descriptor() ([]byte, []int) {
	return file_vpnserver_proto_rawDescGZIP(), []int{9}
}

func (x *StartCloakClientRequest) GetLocalHost() string {
	if x != nil {
		return x.LocalHost
	}
	return ""
}

func (x *StartCloakClientRequest) GetLocalPort() string {
	if x != nil {
		return x.LocalPort
	}
	return ""
}

func (x *StartCloakClientRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StartCloakClientRequest) GetUdp() bool {
	if x != nil {
		return x.Udp
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vpnserver_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_vpnserver_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_vpnserver_proto_rawDescGZIP(), []int{10}
}

var File_vpnserver_proto protoreflect.FileDescriptor

var file_vpnserver_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x0f,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x77, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22,
	0x2d, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x53,
	0x0a, 0x17, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x22, 0x28, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2a, 0x0a,
	0x0e, 0x54, 0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x3f, 0x0a, 0x0f, 0x54, 0x63, 0x70,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3e, 0x0a, 0x0e, 0x55, 0x72,
	0x6c, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x22, 0x3f, 0x0a, 0x0f, 0x55, 0x72,
	0x6c, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x12, 0x43,
	0x6f, 0x75, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x7f, 0x0a, 0x17, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x43, 0x6c, 0x6f, 0x61, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x48, 0x6f, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x64, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x75, 0x64, 0x70, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x32, 0xdf, 0x05, 0x0a, 0x03, 0x56, 0x70, 0x6e, 0x12, 0x38, 0x0a, 0x08, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x41, 0x77, 0x67, 0x12, 0x1a, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x77, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2d, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x77, 0x67,
	0x12, 0x10, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x10, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x40, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x75, 0x74,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1e, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x31, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x70, 0x4f, 0x75,
	0x74, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x10, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x48, 0x0a, 0x10, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x22, 0x2e,
	0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x35, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x70, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x10, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x35, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63,
	0x65, 0x12, 0x40, 0x0a, 0x07, 0x54, 0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x2e, 0x76,
	0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x54, 0x63, 0x70, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x54, 0x63, 0x70, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x55, 0x72, 0x6c, 0x54, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x72, 0x6c, 0x54, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x70, 0x6e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x72, 0x6c, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x6c, 0x64, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x10, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1d, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x43, 0x6f, 0x75, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6c, 0x6f,
	0x61, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6c, 0x6f, 0x61, 0x6b, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x76,
	0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x35,
	0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x70, 0x43, 0x6c, 0x6f, 0x61, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x12, 0x10, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x15, 0x5a, 0x13, 0x67, 0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2f, 0x76, 0x70, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vpnserver_proto_rawDescOnce sync.Once
	file_vpnserver_proto_rawDescData = file_vpnserver_proto_rawDesc
)

func file_vpnserver_proto_rawDescGZIP() []byte {
	file_vpnserver_proto_rawDescOnce.Do(func() {
		file_vpnserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_vpnserver_proto_rawDescData)
	})
	return file_vpnserver_proto_rawDescData
}

var file_vpnserver_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_vpnserver_proto_goTypes = []interface{}{
	(*StartAwgRequest)(nil),         // 0: vpnserver.StartAwgRequest
	(*StartOutlineRequest)(nil),     // 1: vpnserver.StartOutlineRequest
	(*StartHealthCheckRequest)(nil), // 2: vpnserver.StartHealthCheckRequest
	(*StatusResponce)(nil),          // 3: vpnserver.StatusResponce
	(*TcpPingRequest)(nil),          // 4: vpnserver.TcpPingRequest
	(*TcpPingResponce)(nil),         // 5: vpnserver.TcpPingResponce
	(*UrlTestRequest)(nil),          // 6: vpnserver.UrlTestRequest
	(*UrlTestResponce)(nil),         // 7: vpnserver.UrlTestResponce
	(*CouldStartResponce)(nil),      // 8: vpnserver.CouldStartResponce
	(*StartCloakClientRequest)(nil), // 9: vpnserver.StartCloakClientRequest
	(*Empty)(nil),                   // 10: vpnserver.Empty
}
var file_vpnserver_proto_depIdxs = []int32{
	0,  // 0: vpnserver.Vpn.StartAwg:input_type -> vpnserver.StartAwgRequest
	10, // 1: vpnserver.Vpn.StopAwg:input_type -> vpnserver.Empty
	1,  // 2: vpnserver.Vpn.StartOutline:input_type -> vpnserver.StartOutlineRequest
	10, // 3: vpnserver.Vpn.StopOutline:input_type -> vpnserver.Empty
	2,  // 4: vpnserver.Vpn.StartHealthCheck:input_type -> vpnserver.StartHealthCheckRequest
	10, // 5: vpnserver.Vpn.StopHealthCheck:input_type -> vpnserver.Empty
	10, // 6: vpnserver.Vpn.Status:input_type -> vpnserver.Empty
	4,  // 7: vpnserver.Vpn.TcpPing:input_type -> vpnserver.TcpPingRequest
	6,  // 8: vpnserver.Vpn.UrlTest:input_type -> vpnserver.UrlTestRequest
	10, // 9: vpnserver.Vpn.CouldStart:input_type -> vpnserver.Empty
	9,  // 10: vpnserver.Vpn.StartCloakClient:input_type -> vpnserver.StartCloakClientRequest
	10, // 11: vpnserver.Vpn.StopCloakClient:input_type -> vpnserver.Empty
	10, // 12: vpnserver.Vpn.StartAwg:output_type -> vpnserver.Empty
	10, // 13: vpnserver.Vpn.StopAwg:output_type -> vpnserver.Empty
	10, // 14: vpnserver.Vpn.StartOutline:output_type -> vpnserver.Empty
	10, // 15: vpnserver.Vpn.StopOutline:output_type -> vpnserver.Empty
	10, // 16: vpnserver.Vpn.StartHealthCheck:output_type -> vpnserver.Empty
	10, // 17: vpnserver.Vpn.StopHealthCheck:output_type -> vpnserver.Empty
	3,  // 18: vpnserver.Vpn.Status:output_type -> vpnserver.StatusResponce
	5,  // 19: vpnserver.Vpn.TcpPing:output_type -> vpnserver.TcpPingResponce
	7,  // 20: vpnserver.Vpn.UrlTest:output_type -> vpnserver.UrlTestResponce
	8,  // 21: vpnserver.Vpn.CouldStart:output_type -> vpnserver.CouldStartResponce
	10, // 22: vpnserver.Vpn.StartCloakClient:output_type -> vpnserver.Empty
	10, // 23: vpnserver.Vpn.StopCloakClient:output_type -> vpnserver.Empty
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_vpnserver_proto_init() }
func file_vpnserver_proto_init() {
	if File_vpnserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vpnserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartAwgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vpnserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartOutlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vpnserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartHealthCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vpnserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vpnserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TcpPingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vpnserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TcpPingResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vpnserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UrlTestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vpnserver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UrlTestResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vpnserver_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouldStartResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vpnserver_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartCloakClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vpnserver_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vpnserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vpnserver_proto_goTypes,
		DependencyIndexes: file_vpnserver_proto_depIdxs,
		MessageInfos:      file_vpnserver_proto_msgTypes,
	}.Build()
	File_vpnserver_proto = out.File
	file_vpnserver_proto_rawDesc = nil
	file_vpnserver_proto_goTypes = nil
	file_vpnserver_proto_depIdxs = nil
}
