name: Android Build

on:
  workflow_call:

jobs:
  android_build:
    runs-on: ubuntu-latest
    env:
      APP_MAJOR_VERSION: ${{ vars.MAJOR }}
      APP_MINOR_VERSION: ${{ vars.MINOR }}
      APP_MAINTENANCE_VERSION: ${{ vars.MAINTENANCE }}
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up bootstrap Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Build Go from source for Android
        run: |
          GO_VERSION="$(cat .go-version)"
          GO_SRC="/home/vagrant/build/srclib/go"

          sudo rm -rf "$GO_SRC"
          sudo mkdir -p "$(dirname "$GO_SRC")"
          sudo chown -R "$USER:$USER" /home/vagrant

          git clone --depth 1 --branch "go${GO_VERSION}" https://github.com/golang/go.git "$GO_SRC"
          pushd "$GO_SRC/src"
          ./make.bash
          popd

          echo "GOROOT=$GO_SRC" >> "$GITHUB_ENV"
          echo "$GO_SRC/bin" >> "$GITHUB_PATH"
          "$GO_SRC/bin/go" env GOROOT GOVERSION

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: >
            platforms;android-35
            platforms;android-36
            build-tools;36.0.0
            ndk;27.2.12479018

      - name: Install gomobile
        run: |
          cd go_module
          go install golang.org/x/mobile/cmd/gomobile@$(go list -m -f '{{.Version}}' golang.org/x/mobile)
          cd ..
          echo "$HOME/go/bin" >> "$GITHUB_PATH"
          "$HOME/go/bin/gomobile" init

      - name: Bundle Install
        run: |
          bundle install

      - name: Build unsigned via Fastlane
        run: |
          bundle exec fastlane android build_android

      - name: Build & sign via Fastlane
        run: |
          bundle exec fastlane android build_android_and_signing
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: dobbyvpn-android-sign.apk
          path: fastlane/DobbyVPN-v${{ vars.MAJOR }}.${{ vars.MINOR }}.${{ vars.MAINTENANCE }}-sign.apk

      - name: Upload unsigned APK
        uses: actions/upload-artifact@v4
        with:
          name: dobbyvpn-android-unsign.apk
          path: fastlane/DobbyVPN-v${{ vars.MAJOR }}.${{ vars.MINOR }}.${{ vars.MAINTENANCE }}-unsign.apk
