name: Initialize empty F-Droid repository

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  deployments: read
  pages: write
  id-token: write

jobs:
  initialize:
    uses: DobbyVPN/fdroid-repo/.github/workflows/publish.yml@5d9569f23f57ff0675e75ec47e4aa374019f98c4
    secrets:
      FDROID_REPO_KEYSTORE: ${{ secrets.FDROID_REPO_KEYSTORE }}
      FDROID_KEYSTORE_PASSWORD: ${{ secrets.FDROID_KEYSTORE_PASSWORD }}
      FDROID_KEY_PASSWORD: ${{ secrets.FDROID_KEY_PASSWORD }}
    with:
      source_sha: ${{ github.sha }}
      initialize: true
