name: Build desktop installers

on:
  workflow_call:
    inputs:
      app_major_version:
        type: string
        required: true
      app_minor_version:
        type: string
        required: true
      app_maintenance_version:
        type: string
        required: true

jobs:
  build_desktop_installers:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: windows
            runner: windows-latest
          - os: ubuntu
            runner: ubuntu-latest
          - os: macos
            runner: macos-15
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          persist-credentials: false

      - name: Download Windows gRPC vpn service
        uses: actions/download-artifact@v7
        with:
          name: windows_grpcvpnserver.exe
          path: installer/windows/

      - name: Download macOS arm64 gRPC vpn service
        uses: actions/download-artifact@v7
        with:
          name: macos_grpcvpnserver-arm64
          path: installer/macos/services/arm64

      - name: Download macOS amd64 gRPC vpn service
        uses: actions/download-artifact@v7
        with:
          name: macos_grpcvpnserver-amd64
          path: installer/macos/services/amd64

      - name: Add permissions to macOS service executables
        working-directory: installer/macos/
        run: |
          chmod +x services/arm64/macos_grpcvpnserver
          chmod +x services/amd64/macos_grpcvpnserver

      - name: Download Windows built application
        uses: actions/download-artifact@v7
        with:
          name: dobbyVPN-windows.zip
          path: installer/windows/

      - name: Download Linux built application
        uses: actions/download-artifact@v7
        with:
          name: dobbyVPN-linux.deb
          path: installer/linux/

      - name: Download MacOS amd64 built application
        uses: actions/download-artifact@v7
        with:
          name: dobbyVPN-macos-amd64.zip
          path: installer/macos/

      - name: Download MacOS aarch64 built application
        uses: actions/download-artifact@v7
        with:
          name: dobbyVPN-macos-aarch64.zip
          path: installer/macos/

      - name: Build Windows installer - Add msbuild to PATH
        if: matrix.os == 'windows'
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
      
      - name: Build Windows installer - Install WiX
        if: matrix.os == 'windows'
        working-directory: installer/windows
        run: dotnet tool install --global wix --version 6.0.0
        
      - name: Build Windows installer
        if: matrix.os == 'windows'
        working-directory: installer/windows
        run: |
          ./build.bat
        env:
          APP_MAJOR_VERSION: ${{ inputs.app_major_version }}
          APP_MINOR_VERSION: ${{ inputs.app_minor_version }}
          APP_MAINTENANCE_VERSION: ${{ inputs.app_maintenance_version }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Build Linux installer
        if: matrix.os == 'ubuntu'
        working-directory: installer/linux/
        run: |
          echo "[+] Linux installer has already been built"

      - name: Build MacOS installer
        if: matrix.os == 'macos'
        working-directory: installer/macos/
        run: |
          sh build.sh
        env:
          APP_MAJOR_VERSION: ${{ inputs.app_major_version }}
          APP_MINOR_VERSION: ${{ inputs.app_minor_version }}
          APP_MAINTENANCE_VERSION: ${{ inputs.app_maintenance_version }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Upload Windows x86 installer
        if: matrix.os == 'windows'
        uses: actions/upload-artifact@v7
        with:
          name: dobbyVPN-windows-x86.msi
          path: installer/windows/bin/x86/dobbyVPN-windows-x86.msi
          if-no-files-found: error

      - name: Upload Windows amd64 installer
        if: matrix.os == 'windows'
        uses: actions/upload-artifact@v7
        with:
          name: dobbyVPN-windows-amd64.msi
          path: installer/windows/bin/amd64/dobbyVPN-windows-amd64.msi
          if-no-files-found: error

      - name: Upload Windows arm64 installer
        if: matrix.os == 'windows'
        uses: actions/upload-artifact@v7
        with:
          name: dobbyVPN-windows-arm64.msi
          path: installer/windows/bin/arm64/dobbyVPN-windows-arm64.msi
          if-no-files-found: error

      - name: Upload MacOS amd64 installer
        if: matrix.os == 'macos'
        uses: actions/upload-artifact@v7
        with:
          name: dobbyVPN-macos-amd64.pkg
          path: installer/macos/bin/amd64/dobbyVPN-macos-amd64.pkg
          if-no-files-found: error

      - name: Upload MacOS aarch64 installer
        if: matrix.os == 'macos'
        uses: actions/upload-artifact@v7
        with:
          name: dobbyVPN-macos-aarch64.pkg
          path: installer/macos/bin/aarch64/dobbyVPN-macos-aarch64.pkg
          if-no-files-found: error
