name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          check-latest: true

      - name: Vendor Cloak/internal
        run: |
          git clone --depth 1 https://github.com/cbeuw/Cloak tmp
          mkdir -p go_client/modules/Cloak
          cp -r tmp/internal go_client/modules/Cloak/
          rm -rf tmp

      - name: Download Go modules
        run: |
          cd go_client
          go mod download
          cd ..

      - name: Install gomobile & init
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init     

      - name: Fetch gomobile runtime
        run: |
          cd go_client            
          go get golang.org/x/mobile/bind@latest
          cd ..

      - name: Build iOS XCFramework
        run: |
          cd go_client
          GO111MODULE=on gomobile bind -target=ios -o MyLibrary.xcframework ./ios_exports
          cd ..

      - name: Show files
        run: |
          ls -laR go_client

      - name: Upload iOS XCFramework
        uses: actions/upload-artifact@v4
        with:
          name: MyLibrary.xcframework
          path: go_client/MyLibrary.xcframework
