name: Torturer

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  public-cross-platform-contract:
    name: Public cross-platform contract
    permissions:
      contents: read
    uses: DobbyVPN/Torturer/.github/workflows/verify.yml@22b504420cc424795a7abf2e60680f8f477aec35
    with:
      source_repository: ${{ github.event.pull_request.head.repo.full_name }}
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ format('{0}', github.event.pull_request.number) }}
